import { chromium } from "@playwright/test";
const S = process.env.S;
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const logs = [];
page.on("console", (m) => { if (m.type() === "error" || m.type() === "warning") logs.push(`${m.type()}: ${m.text()}`); });
page.on("pageerror", (e) => logs.push(`pageerror: ${e.message}`));
await page.goto("http://127.0.0.1:8000/");
await page.waitForSelector("text=Start from a template");
await page.screenshot({ path: `${S}/home.png` });
await page.click('[data-testid="template-summarise-url"] >> text=Try it');
await page.waitForTimeout(6000);
await page.waitForTimeout(800);
await page.screenshot({ path: `${S}/try.png` });
await page.click('[data-testid="step-summarise"]');
await page.waitForTimeout(500);
await page.screenshot({ path: `${S}/inspect.png` });
console.log(logs.slice(0, 20).join("\n"));
await browser.close();
