"""Agent with tools

A support agent that looks up orders, refunds them with approval, and does sums.

Generated by Easy Chain 0.2.0 from a version 1 flow spec. It needs only
LangChain and LangGraph: `pip install -r requirements.txt`, then
`python agent_with_tools.py '<inputs as JSON>'`.

The compiled graph is `graph`; call `build_graph(checkpointer=...)` to keep Save Points.
Ask a Human steps and tool approvals pause the run (LangGraph interrupt); resume with
Command(resume=...).
"""

import hashlib
import json
import os
import re
import sys
import uuid
from collections.abc import Callable
from typing import Annotated, Any
from urllib.parse import quote

import httpx
from langchain.agents import create_agent
from langchain.agents.middleware import (
    HumanInTheLoopMiddleware,
    ModelCallLimitMiddleware,
    ModelFallbackMiddleware,
    PIIMiddleware,
    SummarizationMiddleware,
    ToolErrorMiddleware,
    ToolRetryMiddleware,
)
from langchain.agents.structured_output import ToolStrategy
from langchain.chat_models import init_chat_model
from langchain_core.messages import HumanMessage
from langchain_core.tools import BaseTool, tool
from langgraph.checkpoint.memory import InMemorySaver
from langgraph.config import get_config, get_store
from langgraph.graph import END, START, StateGraph
from langgraph.types import Command
from pydantic import BaseModel, Field
from typing_extensions import TypedDict

# ── Flow Data ────────────────────────────────────────────────────────────────


class FlowData(TypedDict, total=False):
    """The named fields that steps read and write."""

    order_id: str  # The order number, like A-1001.
    amount: float  # How much to refund, in euros.
    expression: str  # A sum to work out, like 12 * 3.
    question: str
    customer_id: str
    answer: dict[str, Any]
    reply: str
    needs_human: bool


class FlowInput(TypedDict, total=False):
    """What a run takes."""

    question: str
    customer_id: str


class FlowOutput(TypedDict, total=False):
    """What a run returns."""

    reply: str
    needs_human: bool


# ── Helpers ──────────────────────────────────────────────────────────────────


def fill(template: str, data: dict[str, Any]) -> str:
    """Put Flow Data values into {field} and environment variables into {secret:NAME}."""

    def value(match: re.Match[str]) -> str:
        name = match.group(1)
        if name.startswith("secret:"):
            return os.environ.get(name.removeprefix("secret:"), "")
        found = data.get(name)
        return "" if found is None else str(found)

    return re.sub(r"\{((?:secret:)?[A-Za-z_][A-Za-z0-9_]*)\}", value, template)


def fill_url(template: str, data: dict[str, Any]) -> str:
    """Like fill(), but URL-encodes values (except a placeholder that starts the URL)."""
    query_at = template.find("?")

    def value(match: re.Match[str]) -> str:
        text = fill(match.group(0), data)
        if match.start() == 0:
            return text
        in_query = query_at != -1 and match.start() > query_at
        return quote(text, safe="" if in_query else "/")

    return re.sub(r"\{(?:secret:)?[A-Za-z_][A-Za-z0-9_]*\}", value, template)


def as_text(value: Any) -> str:
    """Put a list or object into a prompt as readable text (one list item per paragraph)."""
    if value is None:
        return ""
    if isinstance(value, list):
        return "\n\n".join(as_text(item) for item in value)
    if isinstance(value, dict):
        return json.dumps(value, indent=2, ensure_ascii=False, default=str)
    return str(value)


def fill_json(template: str, data: dict[str, Any]) -> str:
    """Like fill(), but writes values as JSON so quotes and newlines can't break the body.

    "{field}" becomes a JSON string, a bare {field} becomes its JSON value, and a
    placeholder inside a longer string is escaped.
    """
    out: list[str] = []
    in_string = False
    pos = 0
    for match in re.finditer(r"\{(?:secret:)?[A-Za-z_][A-Za-z0-9_]*\}", template):
        literal = template[pos : match.start()]
        for i, char in enumerate(literal):
            if char == '"' and (i == 0 or literal[i - 1] != "\\"):
                in_string = not in_string
        text = fill(match.group(0), data)
        name = match.group(0)[1:-1]
        found = text if name.startswith("secret:") else data.get(name)
        after = template[match.end() : match.end() + 1]
        if in_string and literal.endswith('"') and after == '"':
            out.append(literal[:-1] + json.dumps(text, ensure_ascii=False))
            pos = match.end() + 1
            in_string = False
            continue
        out.append(literal)
        if in_string:
            out.append(json.dumps(text, ensure_ascii=False)[1:-1])
        else:
            out.append(json.dumps(found, ensure_ascii=False, default=str))
        pos = match.end()
    out.append(template[pos:])
    return "".join(out)


def idempotency_key() -> str:
    """A key that stays the same when this step is retried or resumed after a crash."""
    configurable = get_config()["configurable"]
    task = f"{configurable.get('thread_id', '')}|{configurable.get('checkpoint_ns', '')}"
    return hashlib.sha256(task.encode()).hexdigest()[:32]


def run_once(key: str, action: Callable[[], Any]) -> Any:
    """Do a side effect at most once per key, remembering its result in the LangGraph store."""
    store = get_store()
    if store is None:
        return action()
    saved = store.get(("side_effects",), key)
    if saved is not None:
        return saved.value["result"]
    result = action()
    try:
        store.put(("side_effects",), key, {"result": result})
    except (TypeError, ValueError):
        pass  # results that can't be stored as JSON aren't remembered
    return result


def memory_tools(data: dict[str, Any]) -> list[BaseTool]:
    """Long-term memory for an agent: remember facts about the user and recall them later.

    Memories live in the LangGraph store under ("memories", <user>): the `user_id` field
    when the flow has one, otherwise the conversation (thread) id.
    """
    user = data.get("user_id") or get_config()["configurable"].get("thread_id", "anyone")
    namespace = ("memories", str(user))

    @tool("remember", description="Save a fact about the user, to use in later conversations.")
    def remember(fact: str) -> str:
        get_store().put(namespace, uuid.uuid4().hex, {"fact": fact})
        return "Remembered."

    @tool("recall", description="Look up what was remembered about the user before.")
    def recall(query: str = "") -> str:
        facts = [item.value.get("fact", "") for item in get_store().search(namespace, limit=100)]
        if query:
            wanted = set(query.lower().split())
            facts.sort(key=lambda fact: -len(wanted & set(fact.lower().split())))
        return "\n".join(f"- {fact}" for fact in facts[:10]) or "Nothing remembered yet."

    return [remember, recall]


def tell_agent(error: Exception, request: Any) -> str:
    """When a tool fails, tell the agent (so it can try another way) instead of stopping."""
    return f"The tool failed ({type(error).__name__}): {error}"


def ask_in_terminal(request: dict[str, Any]) -> dict[str, Any]:
    """Answer an Ask a Human step in the terminal (Easy Chain's Inbox does this in the app)."""
    if "action_requests" in request:
        # An agent wants to use a tool that needs approval (HumanInTheLoopMiddleware).
        decisions = []
        for action in request["action_requests"]:
            print(f"\nThe agent wants to use {action['name']} with {action['args']}")
            if input("approve? [y/n]> ").strip().lower().startswith("y"):
                decisions.append({"type": "approve"})
            else:
                decisions.append({"type": "reject", "message": input("why not?> ")})
        return {"decisions": decisions}
    print(f"\n{request['question']}")
    for name, value in request.get("show", {}).items():
        print(f"  {name}: {value}")
    kind = request.get("kind", "approve")
    if kind == "answer":
        return {"action": "approve", "value": input("answer> ")}
    if kind == "choose":
        options = request.get("options", [])
        for number, option in enumerate(options, start=1):
            print(f"  {number}. {option}")
        picked = input("choose a number> ").strip()
        index = int(picked) - 1 if picked.isdigit() else 0
        return {"action": "approve", "value": options[index if 0 <= index < len(options) else 0]}
    approved = input("approve? [y/n]> ").strip().lower().startswith("y")
    answer: dict[str, Any] = {"action": "approve" if approved else "reject", "comment": input("comment> ")}
    if kind == "edit" and approved:
        edited = input(f"new {request.get('field')} (leave empty to keep it)> ")
        if edited:
            answer["value"] = edited
    return answer


# ── Steps ────────────────────────────────────────────────────────────────────


SUPPORT_INSTRUCTIONS = """\
You help customer {customer_id} with their orders.
Ask for approval before refunds. Be brief."""


class SupportAnswer(BaseModel):
    """The answer of “Support agent”."""

    reply: str = Field(description="The answer for the customer.")
    needs_human: bool = Field(description="A person should follow up.")


def lookup_order(data: FlowData) -> dict[str, Any]:
    """Web request · Look up an order

    GET https://shop.example.com/api/orders/{order_id}?customer={customer_id} and save the JSON
    data as `order`.
    """
    response = httpx.request(
        "GET",
        fill_url("https://shop.example.com/api/orders/{order_id}?customer={customer_id}", data),
        headers={"User-Agent": "Mozilla/5.0 (compatible; EasyChain/0.1)"},
        timeout=30,
        follow_redirects=True,
    )
    response.raise_for_status()
    return {"order": response.json()}


def lookup_order_tool(data: FlowData) -> BaseTool:
    """Web request “Look up an order” as a tool for agents: lookup_order(order_id)."""

    @tool(
        "lookup_order",
        description="Finds an order by its number and returns its status and items.",
    )
    def run_tool(order_id: Annotated[str, "The order number, like A-1001."]) -> str:
        result = lookup_order({**data, "order_id": order_id})
        return as_text(result.get("order"))

    return run_tool


def refund(data: FlowData) -> dict[str, Any]:
    """Web request · Refund an order

    POST https://shop.example.com/api/refunds and save the JSON data as `refund_receipt`. It
    changes something elsewhere, so it is sent at most once: a retry or a resume after a crash
    reuses the first answer.
    """
    key = idempotency_key()

    def send() -> Any:
        response = httpx.request(
            "POST",
            "https://shop.example.com/api/refunds",
            headers={
                "User-Agent": "Mozilla/5.0 (compatible; EasyChain/0.1)",
                "Content-Type": "application/json",
                "Idempotency-Key": key,
            },
            content=fill_json("{\"order\": \"{order_id}\", \"amount\": {amount}}", data),
            timeout=30,
            follow_redirects=True,
        )
        response.raise_for_status()
        return response.json()

    return {"refund_receipt": run_once(key, send)}


def refund_tool(data: FlowData) -> BaseTool:
    """Web request “Refund an order” as a tool for agents: refund(amount, order_id)."""

    @tool("refund", description="Refunds an order, fully or in part.")
    def run_tool(
        amount: Annotated[float, "How much to refund, in euros."],
        order_id: Annotated[str, "The order number, like A-1001."],
    ) -> str:
        result = refund({**data, "amount": amount, "order_id": order_id})
        return as_text(result.get("refund_receipt"))

    return run_tool


# Code · Calculator (sets result)
def calculate(data):
    """Return the result of a simple sum."""
    left, op, right = data["expression"].split()
    a, b = float(left), float(right)
    return {"result": {"+": a + b, "-": a - b, "*": a * b, "/": a / b}[op]}


def calculate_tool(data: FlowData) -> BaseTool:
    """Code “Calculator” as a tool for agents: calculate(expression)."""

    @tool("calculate", description="Works out a sum.")
    def run_tool(expression: Annotated[str, "A sum to work out, like 12 * 3."]) -> str:
        result = calculate({**data, "expression": expression})
        return as_text(result.get("result"))

    return run_tool


def support(data: FlowData) -> dict[str, Any]:
    """Agent · Support agent

    Works on `question` using openai:gpt-4o-mini and the tools lookup_order, refund and
    calculate, and saves its answer as `answer`.
    """
    agent = create_agent(
        model=init_chat_model("openai:gpt-4o-mini"),
        tools=[
            lookup_order_tool(data),
            refund_tool(data),
            calculate_tool(data),
            *memory_tools(data),
        ],
        system_prompt=fill(SUPPORT_INSTRUCTIONS, data),
        middleware=[
            PIIMiddleware("email", strategy="redact"),
            SummarizationMiddleware(
                init_chat_model("openai:gpt-4o-mini"),
                trigger=("tokens", 4000),
                keep=("messages", 20),
            ),
            HumanInTheLoopMiddleware(
                interrupt_on={"refund": {"allowed_decisions": ["approve", "edit", "reject"]}},
                description_prefix="The agent wants to use a tool that needs your approval",
            ),
            ModelCallLimitMiddleware(run_limit=8, exit_behavior="end"),
            ModelFallbackMiddleware(init_chat_model("anthropic:claude-haiku-4-5")),
            ToolErrorMiddleware(tell_agent),
            ToolRetryMiddleware(max_retries=1, on_failure="error"),
        ],
        response_format=ToolStrategy(SupportAnswer),
        name="support",
    )
    result = agent.invoke(
        {"messages": [HumanMessage(str(data.get("question", "")))]}, {"recursion_limit": 40}
    )
    answer = result["structured_response"].model_dump()
    return {
        "answer": answer,
        "reply": answer["reply"],
        "needs_human": answer["needs_human"],
    }


# ── Flow ─────────────────────────────────────────────────────────────────────


def build_graph(checkpointer=None, *, store=None, cache=None):
    """Wire the steps into a LangGraph graph.

    Pass a checkpointer (for example InMemorySaver()) to keep a Save Point after every step,
    a store to remember side effects across retries, and a cache for cached steps.
    """
    builder = StateGraph(FlowData, input_schema=FlowInput, output_schema=FlowOutput)

    builder.add_node("support", support)

    builder.add_edge(START, "support")
    builder.add_edge("support", END)
    return builder.compile(checkpointer=checkpointer, store=store, cache=cache)


graph = build_graph()


if __name__ == "__main__":
    app = build_graph(checkpointer=InMemorySaver())
    config = {"configurable": {"thread_id": "terminal"}}
    example = {"question": "Where is my order A-1001?", "customer_id": "C-42"}
    inputs = json.loads(sys.argv[1]) if len(sys.argv) > 1 else example
    result = app.invoke(inputs, config)
    while "__interrupt__" in result:
        answer = ask_in_terminal(result["__interrupt__"][0].value)
        result = app.invoke(Command(resume=answer), config)
    print(json.dumps(result, indent=2, ensure_ascii=False, default=str))
