"""Pick a tone

Generated by Easy Chain 0.3.0 from a version 1 flow spec.
It needs only LangChain and LangGraph:
`pip install -r requirements.txt`, then
`python pick_a_tone.py '<inputs as JSON>'`.

The compiled graph is `graph`; call `build_graph(checkpointer=...)` to keep Save Points.
Ask a Human steps and tool approvals pause the run (LangGraph interrupt); resume with
Command(resume=...).
"""

import json
import sys
from typing import Any

from langgraph.checkpoint.memory import InMemorySaver
from langgraph.graph import END, START, StateGraph
from langgraph.types import Command, interrupt
from typing_extensions import TypedDict

# ── Flow Data ────────────────────────────────────────────────────────────────


class FlowData(TypedDict, total=False):
    """The named fields that steps read and write."""

    draft: str
    tone_choice: str
    tone_choice_comment: str
    reply: Any
    extra: str


class FlowInput(TypedDict, total=False):
    """What a run takes."""

    draft: str


class FlowOutput(TypedDict, total=False):
    """What a run returns."""

    reply: Any
    tone_choice: str
    extra: str


# ── Helpers ──────────────────────────────────────────────────────────────────


def pick_option(answer: str, options: list[str]) -> str | None:
    """The option a person picked: the one their answer names exactly (ignoring case and
    spaces), or None."""
    said = " ".join(answer.split()).lower()
    return next((o for o in options if " ".join(o.split()).lower() == said), None)


def ask_in_terminal(request: dict[str, Any]) -> dict[str, Any]:
    """Answer an Ask a Human step in the terminal (Easy Chain's Inbox does this in the app)."""
    if "action_requests" in request:
        # An agent wants to use a tool that needs approval (HumanInTheLoopMiddleware).
        decisions = []
        for action in request["action_requests"]:
            print(f"\nThe agent wants to use {action['name']} with {action['args']}")
            if input("approve? [y/n]> ").strip().lower().startswith("y"):
                decisions.append({"type": "approve"})
            else:
                decisions.append({"type": "reject", "message": input("why not?> ")})
        return {"decisions": decisions}
    print(f"\n{request['question']}")
    for name, value in request.get("show", {}).items():
        print(f"  {name}: {value}")
    kind = request.get("kind", "approve")
    if kind == "answer":
        return {"action": "approve", "value": input("answer> ")}
    if kind == "choose":
        options = request.get("options", [])
        for number, option in enumerate(options, start=1):
            print(f"  {number}. {option}")
        while True:
            picked = input("choose a number> ").strip()
            if picked.isdigit() and 1 <= int(picked) <= len(options):
                return {"action": "approve", "value": options[int(picked) - 1]}
            print(f"Type a number from 1 to {len(options)}.")
    approved = input("approve? [y/n]> ").strip().lower().startswith("y")
    answer: dict[str, Any] = {"action": "approve" if approved else "reject", "comment": input("comment> ")}
    if kind == "edit" and approved:
        edited = input(f"new {request.get('field')} (leave empty to keep it)> ")
        if edited:
            answer["value"] = edited
    return answer


# ── Steps ────────────────────────────────────────────────────────────────────


TONE_OPTIONS = ["Friendly", "Formal"]


def tone(data: FlowData) -> dict[str, Any]:
    """Ask a Human · tone

    Pauses the run (a LangGraph interrupt) until a person picks an option; saves it as
    `tone_choice`. An answer that isn't one of the options is asked again.
    """
    problem = ""  # says why when an answer has to be given again
    while True:
        answer = interrupt(
            {
                "step": "tone",
                "kind": "choose",
                "question": problem + "Which tone should the reply have?",
                "show": {"draft": data.get("draft")},
                "options": TONE_OPTIONS,
            }
        )
        if not isinstance(answer, dict):  # resumed with a bare value
            answer = {"value": answer}
        value = str(answer.get("value") or "")
        choice = pick_option(value, TONE_OPTIONS)
        if choice is not None:
            return {"tone_choice": choice, "tone_choice_comment": str(answer.get("comment") or "")}
        # Not one of the options: ask again (LangGraph matches answers to asks in order).
        problem = f"“{' '.join(value.split())[:60]}” isn't one of the options. "


def route_tone(data: FlowData) -> str:
    """Follow the answer given at "tone"."""
    return data.get("tone_choice") or TONE_OPTIONS[0]


# Code · friendly (sets reply)
def friendly(data):
    return {"reply": "Hi! " + data["draft"]}


# Code · formal (sets reply)
def formal(data):
    return {"reply": "Dear customer, " + data["draft"]}


def note(data: FlowData) -> dict[str, Any]:
    """Ask a Human · note

    Pauses the run (a LangGraph interrupt) until a person answers; saves the answer as `extra`.
    """
    answer = interrupt(
        {
            "step": "note",
            "kind": "answer",
            "question": "Anything to add?",
        }
    )
    if not isinstance(answer, dict):  # resumed with a bare value
        answer = {"value": answer}
    return {"extra": str(answer.get("value") or "")}


# ── Flow ─────────────────────────────────────────────────────────────────────


def build_graph(checkpointer=None, *, store=None, cache=None):
    """Wire the steps into a LangGraph graph.

    Pass a checkpointer (for example InMemorySaver()) to keep a Save Point after every step,
    a store to remember side effects across retries, and a cache for cached steps.
    """
    builder = StateGraph(FlowData, input_schema=FlowInput, output_schema=FlowOutput)

    builder.add_node("tone", tone)
    builder.add_node("friendly", friendly)
    builder.add_node("formal", formal)
    builder.add_node("note", note)

    builder.add_edge(START, "tone")
    builder.add_conditional_edges(
        "tone",
        route_tone,
        {
            "Friendly": "friendly",
            "Formal": "formal",
        },
    )
    builder.add_edge("friendly", "note")
    builder.add_edge("formal", "note")
    builder.add_edge("note", END)
    return builder.compile(checkpointer=checkpointer, store=store, cache=cache)


graph = build_graph()


if __name__ == "__main__":
    app = build_graph(checkpointer=InMemorySaver())
    config = {"configurable": {"thread_id": "terminal"}}
    example = {"draft": "Thanks for writing in."}
    inputs = json.loads(sys.argv[1]) if len(sys.argv) > 1 else example
    result = app.invoke(inputs, config)
    while "__interrupt__" in result:
        answer = ask_in_terminal(result["__interrupt__"][0].value)
        result = app.invoke(Command(resume=answer), config)
    print(json.dumps(result, indent=2, ensure_ascii=False, default=str))
