"""Approve reply

Generated by Easy Chain 0.2.0 from a version 1 flow spec. It needs only
LangChain and LangGraph: `pip install -r requirements.txt`, then
`python approve_reply.py '<inputs as JSON>'`.

The compiled graph is `graph`; call `build_graph(checkpointer=...)` to keep Save Points.
Ask a Human steps pause the run (LangGraph interrupt); resume with Command(resume=...).
"""

import json
import os
import re
import sys
from typing import Any

from langgraph.checkpoint.memory import InMemorySaver
from langgraph.graph import END, START, StateGraph
from langgraph.types import Command, interrupt
from typing_extensions import TypedDict

# ── Flow Data ────────────────────────────────────────────────────────────────


class FlowData(TypedDict, total=False):
    """The named fields that steps read and write."""

    draft: str
    human_answer: str
    human_answer_comment: str
    sent: Any


class FlowInput(TypedDict, total=False):
    """What a run takes."""

    draft: str


class FlowOutput(TypedDict, total=False):
    """What a run returns."""

    sent: Any
    human_answer: str
    human_answer_comment: str
    draft: str


# ── Helpers ──────────────────────────────────────────────────────────────────


def fill(template: str, data: dict[str, Any]) -> str:
    """Put Flow Data values into {field} and environment variables into {secret:NAME}."""

    def value(match: re.Match[str]) -> str:
        name = match.group(1)
        if name.startswith("secret:"):
            return os.environ.get(name.removeprefix("secret:"), "")
        found = data.get(name)
        return "" if found is None else str(found)

    return re.sub(r"\{((?:secret:)?[A-Za-z_][A-Za-z0-9_]*)\}", value, template)


def ask_in_terminal(request: dict[str, Any]) -> dict[str, Any]:
    """Answer an Ask a Human step in the terminal (Easy Chain's Inbox does this in the app)."""
    print(f"\n{request['question']}")
    for name, value in request.get("show", {}).items():
        print(f"  {name}: {value}")
    kind = request.get("kind", "approve")
    if kind == "answer":
        return {"action": "approve", "value": input("answer> ")}
    if kind == "choose":
        options = request.get("options", [])
        for number, option in enumerate(options, start=1):
            print(f"  {number}. {option}")
        picked = input("choose a number> ").strip()
        index = int(picked) - 1 if picked.isdigit() else 0
        return {"action": "approve", "value": options[index if 0 <= index < len(options) else 0]}
    approved = input("approve? [y/n]> ").strip().lower().startswith("y")
    answer: dict[str, Any] = {"action": "approve" if approved else "reject", "comment": input("comment> ")}
    if kind == "edit" and approved:
        edited = input(f"new {request.get('field')} (leave empty to keep it)> ")
        if edited:
            answer["value"] = edited
    return answer


# ── Steps ────────────────────────────────────────────────────────────────────


def review(data: FlowData) -> dict[str, Any]:
    """Ask a Human · review

    Pauses the run (a LangGraph interrupt) until a person edits `draft` and approves or rejects;
    saves the decision as `human_answer`.
    """
    answer = interrupt(
        {
            "step": "review",
            "kind": "edit",
            "question": fill("Send this reply? {draft}", data),
            "show": {"draft": data.get("draft")},
            "field": "draft",
            "value": data.get("draft"),
        }
    )
    if not isinstance(answer, dict):  # resumed with a bare value
        answer = {"value": answer}
    approved = answer.get("action", "approve") == "approve"
    update: dict[str, Any] = {
        "human_answer": "Approved" if approved else "Rejected",
        "human_answer_comment": str(answer.get("comment") or ""),
    }
    if approved and answer.get("value") is not None:
        update["draft"] = answer["value"]
    return update


def route_review(data: FlowData) -> str:
    """Follow the answer given at "review"."""
    return "Approved" if data.get("human_answer") == "Approved" else "Rejected"


# Code · send (sets sent)
def send(data):
    return {"sent": "SENT: " + data["draft"]}


# ── Flow ─────────────────────────────────────────────────────────────────────


def build_graph(checkpointer=None, *, store=None, cache=None):
    """Wire the steps into a LangGraph graph.

    Pass a checkpointer (for example InMemorySaver()) to keep a Save Point after every step,
    a store to remember side effects across retries, and a cache for cached steps.
    """
    builder = StateGraph(FlowData, input_schema=FlowInput, output_schema=FlowOutput)

    builder.add_node("review", review)
    builder.add_node("send", send)

    builder.add_edge(START, "review")
    builder.add_conditional_edges("review", route_review, {"Approved": "send", "Rejected": END})
    builder.add_edge("send", END)
    return builder.compile(checkpointer=checkpointer, store=store, cache=cache)


graph = build_graph()


if __name__ == "__main__":
    app = build_graph(checkpointer=InMemorySaver())
    config = {"configurable": {"thread_id": "terminal"}}
    example = {"draft": "Hello"}
    inputs = json.loads(sys.argv[1]) if len(sys.argv) > 1 else example
    result = app.invoke(inputs, config)
    while "__interrupt__" in result:
        answer = ask_in_terminal(result["__interrupt__"][0].value)
        result = app.invoke(Command(resume=answer), config)
    print(json.dumps(result, indent=2, ensure_ascii=False, default=str))
