"""Tutor

Generated by Easy Chain 0.2.0 from a version 1 flow spec. It needs only
LangChain and LangGraph: `pip install -r requirements.txt`, then
`python tutor.py` to chat in the terminal.

The compiled graph is `graph`; call `build_graph(checkpointer=...)` to keep Save Points.
"""

import json
import sys
from typing import Annotated, Any

from langchain.chat_models import init_chat_model
from langchain_core.messages import AIMessage, AnyMessage
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langgraph.checkpoint.memory import InMemorySaver
from langgraph.graph import END, START, StateGraph
from langgraph.graph.message import add_messages
from typing_extensions import TypedDict

# ── Flow Data ────────────────────────────────────────────────────────────────


class FlowData(TypedDict, total=False):
    """The named fields that steps read and write."""

    messages: Annotated[list[AnyMessage], add_messages]  # The conversation so far; update rule: append
    level: str
    topic: str
    prompt: list[AnyMessage]


class FlowInput(TypedDict, total=False):
    """What a run takes."""

    messages: Annotated[list[AnyMessage], add_messages]  # The conversation so far; update rule: append
    level: str


class FlowOutput(TypedDict, total=False):
    """What a run returns."""

    messages: Annotated[list[AnyMessage], add_messages]  # The conversation so far; update rule: append


INPUT_DEFAULTS: dict[str, Any] = {"level": "beginner"}


# ── Helpers ──────────────────────────────────────────────────────────────────


def pick_exit(reply: str, exits: list[str], otherwise: str) -> str:
    """Match an AI reply to one of a Decision's exit names (ignoring case)."""
    text = reply.strip().strip(".!\"'`*").lower()
    for name in exits:
        if text == name.lower():
            return name
    for name in exits:
        if name.lower() in text:
            return name
    return otherwise


# ── Steps ────────────────────────────────────────────────────────────────────


CLASSIFY_EXITS = ["On topic"]
CLASSIFY_GUIDANCE = """\
Choose the exit that fits best. Reply with the exit name only.

Exits:
- On topic: about maths
- Off topic: none of the above"""


def classify(data: FlowData) -> dict[str, Any]:
    """Decision · On topic?

    Asks openai:gpt-4o-mini which exit fits `messages` and saves it as `topic`.
    """
    model = init_chat_model("openai:gpt-4o-mini", temperature=0)
    reply = model.invoke([("system", CLASSIFY_GUIDANCE), ("human", data["messages"][-1].text if data.get("messages") else "")])
    return {"topic": pick_exit(reply.text, CLASSIFY_EXITS, "Off topic")}


def route_classify(data: FlowData) -> str:
    """Follow the exit the AI picked for "On topic?"."""
    return data.get("topic") or "Off topic"


rules_template = ChatPromptTemplate.from_messages(
    [
        ("system", "You are a patient tutor. Pitch explanations at a {level} level."),
        MessagesPlaceholder("messages"),
    ]
)


def rules(data: FlowData) -> dict[str, Any]:
    """Instructions · rules

    Fills in {level} and saves the prompt messages as `prompt`.
    """
    prompt = rules_template.invoke(
        {
            "level": data.get("level", ""),
            "messages": data.get("messages", []),
        }
    )
    return {"prompt": prompt.to_messages()}


# Code · Polite refusal (sets messages)
def refuse(data):
    return {"messages": [AIMessage("Let's stick to maths!")]}


def reply(data: FlowData) -> dict[str, Any]:
    """AI Model · reply

    Sends `prompt` to openai:gpt-4o-mini and saves the reply as `messages`.
    """
    model = init_chat_model("openai:gpt-4o-mini")
    reply = model.invoke(data["prompt"])
    return {"messages": [reply]}


# ── Flow ─────────────────────────────────────────────────────────────────────


def build_graph(checkpointer=None, *, store=None, cache=None):
    """Wire the steps into a LangGraph graph.

    Pass a checkpointer (for example InMemorySaver()) to keep a Save Point after every step,
    a store to remember side effects across retries, and a cache for cached steps.
    """
    builder = StateGraph(FlowData, input_schema=FlowInput, output_schema=FlowOutput)

    builder.add_node("classify", classify)
    builder.add_node("rules", rules)
    builder.add_node("refuse", refuse)
    builder.add_node("reply", reply)

    builder.add_edge(START, "classify")
    builder.add_conditional_edges(
        "classify",
        route_classify,
        {
            "On topic": "rules",
            "Off topic": "refuse",
        },
    )
    builder.add_edge("rules", "reply")
    builder.add_edge("refuse", END)
    builder.add_edge("reply", END)
    return builder.compile(checkpointer=checkpointer, store=store, cache=cache)


graph = build_graph()


if __name__ == "__main__":
    app = build_graph(checkpointer=InMemorySaver())
    config = {"configurable": {"thread_id": "terminal"}}
    extra = json.loads(sys.argv[1]) if len(sys.argv) > 1 else {"level": "beginner"}
    # Chat in the terminal. Save Points keep the conversation between turns.
    while True:
        try:
            text = input("you> ").strip()
        except (EOFError, KeyboardInterrupt):
            break
        if text:
            result = app.invoke({**INPUT_DEFAULTS, **extra, "messages": [{"role": "user", "content": text}]}, config)
            print("ai>", result["messages"][-1].text)
