"""Route a ticket

Every kind of Decision rule, plus a Pro expression.

Generated by Easy Chain 0.2.0 from a version 1 flow spec. It needs only
LangChain and LangGraph: `pip install -r requirements.txt`, then
`python route_a_ticket.py '<inputs as JSON>'`.

The compiled graph is `graph`; call `build_graph(checkpointer=...)` to keep Save Points.
"""

import json
import re
import sys
from typing import Any

from langgraph.graph import END, START, StateGraph
from typing_extensions import TypedDict

# ── Flow Data ────────────────────────────────────────────────────────────────


class FlowData(TypedDict, total=False):
    """The named fields that steps read and write."""

    subject: str
    priority: float
    urgent: bool
    tags: list[Any]
    handled: Any


class FlowInput(TypedDict, total=False):
    """What a run takes."""

    subject: str
    priority: float
    urgent: bool
    tags: list[Any]


class FlowOutput(TypedDict, total=False):
    """What a run returns."""

    handled: Any


# ── Steps ────────────────────────────────────────────────────────────────────


def route(data: FlowData) -> dict[str, Any]:
    """Decision · Where should it go?

    Changes no data; route_route below picks the exit.
    """
    return {}


def route_route(data: FlowData) -> str:
    """Pick the exit for the Decision "Where should it go?"."""
    if "refund" in str(data.get("subject") or "").lower():
        return "Refund"
    if str(data.get("subject") or "").strip().lower() == "hello":
        return "Exact"
    if str(data.get("subject") or "").strip().lower() != "hello":
        return "Not hello"
    if float(data.get("priority") or 0) > 7:
        return "High"
    if float(data.get("priority") or 0) < 2:
        return "Low"
    if data.get("priority") == 5:
        return "Same priority"
    if bool(data.get("urgent")):
        return "Urgent"
    if not data.get("urgent"):
        return "Calm"
    if "vip" in (data.get("tags") or []):
        return "VIP"
    if not data.get("tags"):
        return "No tags"
    if bool(data.get("tags")):
        return "Some tags"
    if str(data.get("subject") or "").lower().startswith("re:"):
        return "Re"
    if str(data.get("subject") or "").lower().endswith("?"):
        return "Question"
    if re.search(r"#\d+", str(data.get("subject") or ""), re.IGNORECASE) is not None:
        return "Order number"
    if len(data.get("subject") or "") > 80:
        return "Long"
    if len(data.get("subject") or "") < 3:
        return "Short"
    if "refund" not in str(data.get("subject") or "").lower():
        return "No refund"
    if bool(data.get("urgent")) is True:
        return "Flag"
    if len(data.get("subject")) > 10 and data.get("priority") >= 3:
        return "Expression"
    return "Everything else"


# Code · Handle it (sets handled)
def handle(data):
    return {"handled": True}


# ── Flow ─────────────────────────────────────────────────────────────────────


def build_graph(checkpointer=None, *, store=None, cache=None):
    """Wire the steps into a LangGraph graph.

    Pass a checkpointer (for example InMemorySaver()) to keep a Save Point after every step,
    a store to remember side effects across retries, and a cache for cached steps.
    """
    builder = StateGraph(FlowData, input_schema=FlowInput, output_schema=FlowOutput)

    builder.add_node("route", route)
    builder.add_node("handle", handle)

    builder.add_edge(START, "route")
    builder.add_conditional_edges(
        "route",
        route_route,
        {
            "Refund": "handle",
            "Exact": END,
            "Not hello": END,
            "High": END,
            "Low": END,
            "Same priority": END,
            "Urgent": END,
            "Calm": END,
            "VIP": END,
            "No tags": END,
            "Some tags": END,
            "Re": END,
            "Question": END,
            "Order number": END,
            "Long": END,
            "Short": END,
            "No refund": END,
            "Flag": END,
            "Expression": END,
            "Everything else": END,
        },
    )
    builder.add_edge("handle", END)
    return builder.compile(checkpointer=checkpointer, store=store, cache=cache)


graph = build_graph()


if __name__ == "__main__":
    example = {"subject": "", "priority": 1}
    inputs = json.loads(sys.argv[1]) if len(sys.argv) > 1 else example
    result = graph.invoke(inputs)
    print(json.dumps(result, indent=2, ensure_ascii=False, default=str))
