"""Shout topics

Generated by Easy Chain 0.1.0 from a version 1 flow spec. It needs only
LangChain and LangGraph: `pip install -r requirements.txt`, then
`python shout_topics.py '<inputs as JSON>'`.

The compiled graph is `graph`; call `build_graph(checkpointer=...)` to keep Save Points.
"""

import json
import sys
from typing import Annotated, Any

from langgraph.graph import END, START, StateGraph
from langgraph.types import Send
from typing_extensions import TypedDict

# ── Flow Data ────────────────────────────────────────────────────────────────


def collect_items(old: list[Any] | None, new: list[Any] | None) -> list[Any]:
    """Update rule for For Each results: None starts a new list, anything else is added."""
    if new is None:
        return []
    return (old or []) + new


class FlowData(TypedDict, total=False):
    """The named fields that steps read and write."""

    topics: list[Any]
    each_results: Annotated[list[Any], collect_items]  # Results collected by “each” while it runs.
    each_index: float  # The item “each” is working on.
    topic: Any
    shouted: list[Any]
    loud: Any


class FlowInput(TypedDict, total=False):
    """What a run takes."""

    topics: list[Any]


class FlowOutput(TypedDict, total=False):
    """What a run returns."""

    shouted: list[Any]


RUN_CONFIG: dict[str, Any] = {"max_concurrency": 2}


# ── Steps ────────────────────────────────────────────────────────────────────


def each(data: FlowData) -> dict[str, Any]:
    """For Each · each

    Starts a new list of results; send_each below sends each item of `topics` to `shout`.
    """
    return {"each_results": None}  # None starts the list again


def send_each(data: FlowData) -> list[Send] | str:
    """Send every item of `topics` to its own run of the step (they run side by side)."""
    items = data.get("topics")
    if items is None:
        items = []
    elif not isinstance(items, list):
        items = [items]
    if not items:
        return "each__done"
    return [
        Send("shout", {**data, "topic": item, "each_index": number})
        for number, item in enumerate(items)
    ]


def shout_for_each(data: FlowData) -> dict[str, Any]:
    """Run `shout` for one item of “each” and keep `loud`."""
    result = shout(data) or {}
    return {"each_results": [(data["each_index"], result.get("loud"))]}


def each_done(data: FlowData) -> dict[str, Any]:
    """Put the results of “each” in item order and save them as `shouted`."""
    collected = sorted(data.get("each_results") or [], key=lambda pair: pair[0])
    return {"shouted": [result for _, result in collected]}


# Code · shout (sets loud)
def shout(data):
    return {"loud": data["topic"].upper()}


# ── Flow ─────────────────────────────────────────────────────────────────────


def build_graph(checkpointer=None, *, store=None, cache=None):
    """Wire the steps into a LangGraph graph.

    Pass a checkpointer (for example InMemorySaver()) to keep a Save Point after every step,
    a store to remember side effects across retries, and a cache for cached steps.
    """
    builder = StateGraph(FlowData, input_schema=FlowInput, output_schema=FlowOutput)

    builder.add_node("each", each)
    builder.add_node("each__done", each_done, defer=True)
    builder.add_node("shout", shout_for_each)

    builder.add_edge(START, "each")
    builder.add_conditional_edges("each", send_each, ["shout", "each__done"])
    builder.add_edge("each__done", END)
    builder.add_edge("shout", "each__done")
    return builder.compile(checkpointer=checkpointer, store=store, cache=cache)


graph = build_graph()


if __name__ == "__main__":
    example = {"topics": ["a", "b", "c"]}
    inputs = json.loads(sys.argv[1]) if len(sys.argv) > 1 else example
    result = graph.invoke(inputs, RUN_CONFIG)
    print(json.dumps(result, indent=2, ensure_ascii=False, default=str))
