"""Search an API

Generated by Easy Chain 0.3.0 from a version 1 flow spec.
It needs only LangChain and LangGraph:
`pip install -r requirements.txt`, then
`python search_an_api.py '<inputs as JSON>'`.

The compiled graph is `graph`; call `build_graph(checkpointer=...)` to keep Save Points.
"""

import hashlib
import json
import os
import re
import sys
from collections.abc import Callable
from typing import Any
from urllib.parse import quote

import httpx
from langgraph.config import get_config, get_store
from langgraph.graph import END, START, StateGraph
from typing_extensions import TypedDict

# ── Flow Data ────────────────────────────────────────────────────────────────


class FlowData(TypedDict, total=False):
    """The named fields that steps read and write."""

    question: str
    limit: float
    results: Any
    robots: str


class FlowInput(TypedDict, total=False):
    """What a run takes."""

    question: str
    limit: float


class FlowOutput(TypedDict, total=False):
    """What a run returns."""

    results: Any
    robots: str


INPUT_DEFAULTS: dict[str, Any] = {"limit": 5}


# ── Helpers ──────────────────────────────────────────────────────────────────


def fill(template: str, data: dict[str, Any]) -> str:
    """Put Flow Data values into {field} and environment variables into {secret:NAME}."""

    def value(match: re.Match[str]) -> str:
        name = match.group(1)
        if name.startswith("secret:"):
            return os.environ.get(name.removeprefix("secret:"), "")
        found = data.get(name)
        return "" if found is None else str(found)

    return re.sub(r"\{((?:secret:)?[A-Za-z_][A-Za-z0-9_]*)\}", value, template)


def fill_url(template: str, data: dict[str, Any]) -> str:
    """Like fill(), but URL-encodes every value, "/" included, so no value can change which
    address is called. A placeholder that starts the URL (a base address such as {base_url})
    is used as it is. A value that would make a part of the path empty, "." or ".." is refused.
    """
    placeholder = r"\{(?:secret:)?[A-Za-z_][A-Za-z0-9_]*\}"

    def encoded(text: str) -> str:
        return re.sub(placeholder, lambda m: quote(fill(m.group(0), data), safe=""), text)

    start = ""
    first = re.match(placeholder, template)
    if first:
        start, template = fill(first.group(0), data), template[first.end() :]
    path, mark, query = template.partition("?")
    parts = []
    for part in path.split("/"):
        filled = encoded(part)
        if filled != part and filled in ("", ".", ".."):
            shown = f"“{filled}”" if filled else "empty"
            raise ValueError(
                f"{part} in the URL is {shown}, which would call a different address. "
                "Give it a real value."
            )
        parts.append(filled)
    return start + "/".join(parts) + mark + encoded(query)


def fill_json(template: str, data: dict[str, Any]) -> str:
    """Like fill(), but writes values as JSON so quotes and newlines can't break the body.

    "{field}" becomes a JSON string, a bare {field} becomes its JSON value, and a
    placeholder inside a longer string is escaped.
    """
    out: list[str] = []
    in_string = False
    pos = 0
    for match in re.finditer(r"\{(?:secret:)?[A-Za-z_][A-Za-z0-9_]*\}", template):
        literal = template[pos : match.start()]
        for i, char in enumerate(literal):
            if char == '"' and (i == 0 or literal[i - 1] != "\\"):
                in_string = not in_string
        text = fill(match.group(0), data)
        name = match.group(0)[1:-1]
        found = text if name.startswith("secret:") else data.get(name)
        after = template[match.end() : match.end() + 1]
        if in_string and literal.endswith('"') and after == '"':
            out.append(literal[:-1] + json.dumps(text, ensure_ascii=False))
            pos = match.end() + 1
            in_string = False
            continue
        out.append(literal)
        if in_string:
            out.append(json.dumps(text, ensure_ascii=False)[1:-1])
        else:
            out.append(json.dumps(found, ensure_ascii=False, default=str))
        pos = match.end()
    out.append(template[pos:])
    return "".join(out)


def idempotency_key() -> str:
    """A key that stays the same when this step is retried or resumed after a crash."""
    configurable = get_config()["configurable"]
    task = f"{configurable.get('thread_id', '')}|{configurable.get('checkpoint_ns', '')}"
    return hashlib.sha256(task.encode()).hexdigest()[:32]


def run_once(key: str, action: Callable[[], Any]) -> Any:
    """Do a side effect at most once per key, remembering its result in the LangGraph store."""
    store = get_store()
    if store is None:
        return action()
    saved = store.get(("side_effects",), key)
    if saved is not None:
        return saved.value["result"]
    result = action()
    try:
        store.put(("side_effects",), key, {"result": result})
    except (TypeError, ValueError):
        pass  # results that can't be stored as JSON aren't remembered
    return result


# ── Steps ────────────────────────────────────────────────────────────────────


def search(data: FlowData) -> dict[str, Any]:
    """Web request · Search

    POST https://api.example.com/search?limit={limit} and save the JSON data as `results`. It
    changes something elsewhere, so it is sent at most once: a retry or a resume after a crash
    reuses the first answer.
    """
    key = idempotency_key()

    def send() -> Any:
        response = httpx.request(
            "POST",
            fill_url("https://api.example.com/search?limit={limit}", data),
            headers={
                "User-Agent": "Mozilla/5.0 (compatible; EasyChain/0.1)",
                "Content-Type": "application/json",
                "Authorization": fill("Bearer {secret:SEARCH_API_KEY}", data),
                "X-Client": "easychain",
                "Idempotency-Key": key,
            },
            content=fill_json("{\"query\": \"{question}\", \"filters\": {\"lang\": \"en\"}}", data),
            timeout=10.0,
            follow_redirects=True,
        )
        response.raise_for_status()
        return response.json()

    return {"results": run_once(key, send)}


def raw(data: FlowData) -> dict[str, Any]:
    """Web request · Raw text

    GET https://example.com/robots.txt and save the response as `robots`.
    """
    response = httpx.request(
        "GET",
        "https://example.com/robots.txt",
        headers={"User-Agent": "Mozilla/5.0 (compatible; EasyChain/0.1)"},
        timeout=30,
        follow_redirects=True,
    )
    response.raise_for_status()
    return {"robots": response.text[:500]}


# ── Flow ─────────────────────────────────────────────────────────────────────


def build_graph(checkpointer=None, *, store=None, cache=None):
    """Wire the steps into a LangGraph graph.

    Pass a checkpointer (for example InMemorySaver()) to keep a Save Point after every step,
    a store to remember side effects across retries, and a cache for cached steps.
    """
    builder = StateGraph(FlowData, input_schema=FlowInput, output_schema=FlowOutput)

    builder.add_node("search", search)
    builder.add_node("raw", raw)

    builder.add_edge(START, "search")
    builder.add_edge("search", "raw")
    builder.add_edge("raw", END)
    return builder.compile(checkpointer=checkpointer, store=store, cache=cache)


graph = build_graph()


if __name__ == "__main__":
    example = {"question": "What is LangGraph?", "limit": 5}
    inputs = json.loads(sys.argv[1]) if len(sys.argv) > 1 else example
    result = graph.invoke({**INPUT_DEFAULTS, **inputs})
    print(json.dumps(result, indent=2, ensure_ascii=False, default=str))
