"""Extract JSON

Generated by Easy Chain 0.2.0 from a version 1 flow spec. It needs only
LangChain and LangGraph: `pip install -r requirements.txt`, then
`python extract_json.py '<inputs as JSON>'`.

The compiled graph is `graph`; call `build_graph(checkpointer=...)` to keep Save Points.
"""

import json
import sys
from typing import Any

from langchain.chat_models import init_chat_model
from langchain_core.messages import AnyMessage
from langchain_core.prompts import ChatPromptTemplate
from langgraph.graph import END, START, StateGraph
from typing_extensions import TypedDict

# ── Flow Data ────────────────────────────────────────────────────────────────


class FlowData(TypedDict, total=False):
    """The named fields that steps read and write."""

    text: str
    messages_for_ai: list[AnyMessage]
    json_text: str
    person: Any


class FlowInput(TypedDict, total=False):
    """What a run takes."""

    text: str


class FlowOutput(TypedDict, total=False):
    """What a run returns."""

    person: Any


# ── Steps ────────────────────────────────────────────────────────────────────


PROMPT_SYSTEM = """\
Extract the person's name and age as JSON like {{"name": "Ada", "age": 36}}.
Never add other keys."""

prompt_template = ChatPromptTemplate.from_messages(
    [
        ("system", PROMPT_SYSTEM),
        ("human", "Bob is 40 years old."),
        ("ai", "{{\"name\": \"Bob\", \"age\": 40}}"),
        ("human", "{text}"),
    ]
)


def prompt(data: FlowData) -> dict[str, Any]:
    """Instructions · Explain the format

    Fills in {text} and saves the prompt messages as `messages_for_ai`.
    """
    prompt = prompt_template.invoke({"text": data.get("text", "")})
    return {"messages_for_ai": prompt.to_messages()}


def extract(data: FlowData) -> dict[str, Any]:
    """AI Model · Extract

    Sends `messages_for_ai` to anthropic:claude-haiku-4-5 and saves the reply as `json_text`.
    """
    model = init_chat_model("anthropic:claude-haiku-4-5", max_tokens=200)
    reply = model.invoke(data["messages_for_ai"])
    return {"json_text": reply.text}


# Code · Parse JSON (sets person)
def parse(data):
    raw = data["json_text"]
    try:
        value = json.loads(raw)
    except json.JSONDecodeError:
        value = {}
    return {"person": value}


# ── Flow ─────────────────────────────────────────────────────────────────────


def build_graph(checkpointer=None, *, store=None, cache=None):
    """Wire the steps into a LangGraph graph.

    Pass a checkpointer (for example InMemorySaver()) to keep a Save Point after every step,
    a store to remember side effects across retries, and a cache for cached steps.
    """
    builder = StateGraph(FlowData, input_schema=FlowInput, output_schema=FlowOutput)

    builder.add_node("prompt", prompt)
    builder.add_node("extract", extract)
    builder.add_node("parse", parse)

    builder.add_edge(START, "prompt")
    builder.add_edge("prompt", "extract")
    builder.add_edge("extract", "parse")
    builder.add_edge("parse", END)
    return builder.compile(checkpointer=checkpointer, store=store, cache=cache)


graph = build_graph()


if __name__ == "__main__":
    example = {"text": ""}
    inputs = json.loads(sys.argv[1]) if len(sys.argv) > 1 else example
    result = graph.invoke(inputs)
    print(json.dumps(result, indent=2, ensure_ascii=False, default=str))
