"""Count up

Generated by Easy Chain 0.2.0 from a version 1 flow spec. It needs only
LangChain and LangGraph: `pip install -r requirements.txt`, then
`python count_up.py '<inputs as JSON>'`.

The compiled graph is `graph`; call `build_graph(checkpointer=...)` to keep Save Points.
"""

import json
import os
import re
import sys
from typing import Any

from langgraph.graph import END, START, StateGraph
from langgraph.types import Command
from typing_extensions import TypedDict

# ── Flow Data ────────────────────────────────────────────────────────────────


class FlowData(TypedDict, total=False):
    """The named fields that steps read and write."""

    count: float
    limit: float
    check_rounds: float  # How many times “check” has run in this run.
    note: str


class FlowInput(TypedDict, total=False):
    """What a run takes."""

    limit: float
    check_rounds: float  # How many times “check” has run in this run.


class FlowOutput(TypedDict, total=False):
    """What a run returns."""

    count: float
    note: str


# Loop round counters; every new run starts them again.
ROUND_COUNTERS: dict[str, Any] = {"check_rounds": 0}


# ── Helpers ──────────────────────────────────────────────────────────────────


def fill(template: str, data: dict[str, Any]) -> str:
    """Put Flow Data values into {field} and environment variables into {secret:NAME}."""

    def value(match: re.Match[str]) -> str:
        name = match.group(1)
        if name.startswith("secret:"):
            return os.environ.get(name.removeprefix("secret:"), "")
        found = data.get(name)
        return "" if found is None else str(found)

    return re.sub(r"\{((?:secret:)?[A-Za-z_][A-Za-z0-9_]*)\}", value, template)


# ── Steps ────────────────────────────────────────────────────────────────────


def bump(data: FlowData) -> Command:
    """Jump · bump

    Sets `count`, `note` (in order), then picks the next step.
    """
    data = {**data}  # later fields see the earlier ones
    data["count"] = (data.get("count") or 0) + 1
    data["note"] = fill("round {count}", data)
    update = {name: data[name] for name in ("count", "note")}
    if data.get("count") < data.get("limit"):
        return Command(update=update, goto="check")
    return Command(update=update, goto=END)


def check(data: FlowData) -> dict[str, Any]:
    """Decision · check

    Counts the rounds in `check_rounds`; route_check below picks the exit.
    """
    return {"check_rounds": data.get("check_rounds", 0) + 1}


def route_check(data: FlowData) -> str:
    """Pick the exit for the Decision "check"."""
    if data.get("check_rounds", 0) >= 2:  # round limit reached
        return "Stop"
    if float(data.get("count") or 0) > -1:
        return "Loop"
    return "Stop"


# ── Flow ─────────────────────────────────────────────────────────────────────


def build_graph(checkpointer=None, *, store=None, cache=None):
    """Wire the steps into a LangGraph graph.

    Pass a checkpointer (for example InMemorySaver()) to keep a Save Point after every step,
    a store to remember side effects across retries, and a cache for cached steps.
    """
    builder = StateGraph(FlowData, input_schema=FlowInput, output_schema=FlowOutput)

    builder.add_node("bump", bump, destinations=("check", END))
    builder.add_node("check", check)

    builder.add_edge(START, "bump")
    builder.add_conditional_edges("check", route_check, {"Loop": "bump", "Stop": END})
    return builder.compile(checkpointer=checkpointer, store=store, cache=cache)


graph = build_graph()


if __name__ == "__main__":
    example = {"limit": 3}
    inputs = json.loads(sys.argv[1]) if len(sys.argv) > 1 else example
    result = graph.invoke({**ROUND_COUNTERS, **inputs})
    print(json.dumps(result, indent=2, ensure_ascii=False, default=str))
