"""Answer from the docs

Finds passages in the product docs and answers with citations.

Generated by Easy Chain 0.3.0 from a version 1 flow spec.
It needs LangChain, LangGraph and sqlalchemy, numpy, psycopg:
`pip install -r requirements.txt`, then
`python answer_from_the_docs.py '<inputs as JSON>'`.

The compiled graph is `graph`; call `build_graph(checkpointer=...)` to keep Save Points.
"""

import hashlib
import json
import math
import os
import re
import sys
from typing import Any

import numpy as np
import sqlalchemy as sa
from langchain.agents import create_agent
from langchain.agents.middleware import ToolErrorMiddleware
from langchain.chat_models import init_chat_model
from langchain.embeddings import init_embeddings
from langchain_core.embeddings import Embeddings
from langchain_core.messages import AnyMessage, HumanMessage
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.tools import BaseTool, tool
from langgraph.graph import END, START, StateGraph
from typing_extensions import TypedDict

# ── Flow Data ────────────────────────────────────────────────────────────────


class FlowData(TypedDict, total=False):
    """The named fields that steps read and write."""

    question: str
    context: str
    sources: list[Any]
    prompt: list[AnyMessage]
    answer: str
    research: str


class FlowInput(TypedDict, total=False):
    """What a run takes."""

    question: str


class FlowOutput(TypedDict, total=False):
    """What a run returns."""

    answer: str
    sources: list[Any]
    research: str


# ── Helpers ──────────────────────────────────────────────────────────────────


KNOWLEDGE_ENGINES: dict[Any, Any] = {}


KNOWLEDGE_VECTORS: dict[Any, Any] = {}


def knowledge_engine() -> sa.Engine:
    """The database that holds the Knowledge Bases (a synchronous SQLAlchemy engine)."""
    url = os.environ.get("EASYCHAIN_KNOWLEDGE_URL") or os.environ.get("EASYCHAIN_DATABASE_URL")
    if not url:
        home = os.environ.get("EASYCHAIN_HOME") or os.path.expanduser("~/.easychain")
        url = f"sqlite:///{os.path.join(home, 'easychain.db')}"
    if url not in KNOWLEDGE_ENGINES:
        scheme, _, rest = url.partition("://")
        if scheme.split("+")[0] in ("postgresql", "postgres"):
            engine = sa.create_engine(f"postgresql+psycopg://{rest}", pool_pre_ping=True)
        else:
            engine = sa.create_engine(f"sqlite://{rest}", connect_args={"timeout": 30})
        KNOWLEDGE_ENGINES[url] = engine
    return KNOWLEDGE_ENGINES[url]


def knowledge_words(query: str) -> list[str]:
    """The words of a question that say what it's about, for full-text search."""
    common_words = (
        "a an and are as at be but by can could did do does for from get got had has have how "
        "i if in into is it its me my no not of on or our so than that the their them then "
        "there these they this to too us was we were what when where which who why will with "
        "would you your about any some please tell know"
    )
    common = set(common_words.split())
    words = [w for w in re.findall(r"[a-z0-9]+", query.lower()) if len(w) > 1]
    return [w for w in words if w not in common][:30]


def knowledge_vector_kind(dims: int) -> str | None:
    """The pgvector type a Knowledge Base's embeddings are indexed and searched as.

    pgvector's HNSW index takes vectors of up to 2,000 numbers. Bigger ones (3,072 from
    text-embedding-3-large) are indexed at half precision (halfvec), which goes up to
    4,000. None means too big to index: search then compares every embedding.
    """
    if dims <= 2000:
        return "vector"
    if dims <= 4000:
        return "halfvec"
    return None


def knowledge_by_meaning(
    conn: Any, base: str, vector: list[float], limit: int
) -> list[tuple[str, float]]:
    """(chunk id, cosine similarity) for the embeddings closest to the question's."""
    if conn.dialect.name == "postgresql":
        found = conn.execute(
            sa.text(
                "SELECT format_type(atttypid, atttypmod), to_regtype('halfvec') IS NOT NULL "
                "FROM pg_attribute WHERE attrelid = 'kb_chunks'::regclass AND attname = 'embedding'"
            )
        ).first()
        if found and found[0] and found[0].startswith("vector"):
            dims = len(vector)
            distance = f"(embedding::vector({dims})) <=> CAST(:q AS vector({dims}))"
            # Order by the same expression the Knowledge Base's index uses, so it is used.
            kind = knowledge_vector_kind(dims)
            if kind == "halfvec" and found[1]:
                order = f"(embedding::halfvec({dims})) <=> CAST(:q AS halfvec({dims}))"
            else:
                order = distance
            sql = (
                f"SELECT id, 1 - ({distance}) FROM kb_chunks WHERE kb_id = :kb "
                f"AND embedding IS NOT NULL ORDER BY {order} LIMIT :n"
            )
            q = "[" + ",".join(f"{v:.7f}" for v in vector) + "]"
            rows = conn.execute(sa.text(sql), {"kb": base, "q": q, "n": limit})
            return [(r[0], float(r[1])) for r in rows]
    # Without pgvector: compare against every chunk with numpy (fine for thousands of chunks).
    stamp = conn.execute(
        sa.text("SELECT updated_at FROM kb_bases WHERE id = :kb"), {"kb": base}
    ).scalar()
    key = (str(conn.engine.url), base)
    cached = KNOWLEDGE_VECTORS.get(key)
    if cached is None or cached[0] != stamp:
        rows = conn.execute(
            sa.text(
                "SELECT id, embedding FROM kb_chunks WHERE kb_id = :kb AND embedding IS NOT NULL"
            ),
            {"kb": base},
        ).all()
        ids = [r[0] for r in rows]
        matrix = (
            np.vstack([np.frombuffer(bytes(r[1]), dtype=np.float32) for r in rows])
            if rows
            else np.zeros((0, len(vector)), dtype=np.float32)
        )
        norms = np.linalg.norm(matrix, axis=1, keepdims=True)
        matrix = matrix / np.where(norms == 0, 1, norms)
        cached = KNOWLEDGE_VECTORS[key] = (stamp, ids, matrix)
    _, ids, matrix = cached
    if not ids or matrix.shape[1] != len(vector):
        return []
    q = np.asarray(vector, dtype=np.float32)
    q = q / (np.linalg.norm(q) or 1.0)
    scores = matrix @ q
    order = np.argsort(-scores)[:limit]
    return [(ids[i], float(scores[i])) for i in order]


def knowledge_by_words(conn: Any, base: str, query: str, limit: int) -> list[str]:
    """Chunk ids that share the most (and the rarest) words with the question."""
    words = knowledge_words(query)
    if not words:
        return []
    if conn.dialect.name == "postgresql":
        q = " | ".join(words)
        sql = (
            "SELECT id FROM kb_chunks WHERE kb_id = :kb AND tsv @@ to_tsquery('english', :q) "
            "ORDER BY ts_rank_cd(tsv, to_tsquery('english', :q)) DESC LIMIT :n"
        )
        return [r[0] for r in conn.execute(sa.text(sql), {"kb": base, "q": q, "n": limit})]
    match = " OR ".join(f'"{w}"' for w in words)
    sql = (
        "SELECT chunk_id FROM kb_chunks_fts WHERE kb_chunks_fts MATCH :q AND kb_id = :kb "
        "ORDER BY bm25(kb_chunks_fts) LIMIT :n"
    )
    return [r[0] for r in conn.execute(sa.text(sql), {"kb": base, "q": match, "n": limit})]


def search_knowledge(
    base: str,
    query: str,
    embeddings: Any,
    top_k: int = 4,
    mode: str = "hybrid",
    min_similarity: float = 0.0,
) -> list[dict[str, Any]]:
    """The passages of a Knowledge Base that best match a question, best first.

    mode: "hybrid" (meaning and words, merged by reciprocal rank fusion), "meaning"
    (embeddings only) or "words" (full-text search only). min_similarity drops passages
    found only by meaning that are less similar than this (0 to 1), so an unrelated
    question can come back with nothing.
    """
    if not query.strip():
        return []
    engine = knowledge_engine()
    pool = max(top_k * 4, 20)
    scores: dict[str, float] = {}
    with engine.connect() as conn:
        by_words = knowledge_by_words(conn, base, query, pool) if mode != "meaning" else []
        by_meaning = []
        if mode != "words":
            near = knowledge_by_meaning(conn, base, embeddings.embed_query(query), pool)
            worded = set(by_words)
            by_meaning = [(cid, sim) for cid, sim in near if sim >= min_similarity or cid in worded]
        similarity = dict(by_meaning)
        for ids in ([cid for cid, _ in by_meaning], by_words):
            for rank, chunk_id in enumerate(ids, start=1):
                scores[chunk_id] = scores.get(chunk_id, 0.0) + 1.0 / (60 + rank)
        best = sorted(scores, key=lambda cid: scores[cid], reverse=True)[:top_k]
        if not best:
            return []
        rows = conn.execute(
            sa.text(
                "SELECT id, doc_id, text, title, source, page, heading FROM kb_chunks "
                "WHERE id IN :ids"
            ).bindparams(sa.bindparam("ids", expanding=True)),
            {"ids": best},
        ).mappings()
        by_id = {row["id"]: dict(row) for row in rows}
    words = set(by_words)
    hits = []
    for cid in best:
        if cid not in by_id:
            continue
        hit = by_id[cid] | {"score": round(scores[cid], 5)}
        if cid in similarity:
            hit["similarity"] = round(similarity[cid], 3)
        hit["matched"] = (
            "both" if cid in similarity and cid in words else "words" if cid in words else "meaning"
        )
        hits.append(hit)
    return [{"n": n, **hit} for n, hit in enumerate(hits, start=1)]


def cite_passages(hits: list[dict[str, Any]]) -> str:
    """Passages numbered for citing: "[1] Title (source, page 3)" then the text."""
    blocks = []
    for hit in hits:
        where = ", ".join(
            part
            for part in (hit.get("source") or "", f"page {hit['page']}" if hit.get("page") else "")
            if part
        )
        title = hit.get("title") or "Untitled"
        heading = hit.get("heading")
        if heading and heading.lower() not in title.lower():
            title = f"{title} › {heading}"
        header = f"[{hit['n']}] {title}" + (f" ({where})" if where else "")
        blocks.append(f"{header}\n{hit['text'].strip()}")
    return "\n\n".join(blocks)


def rerank_passages(
    model: Any, query: str, hits: list[dict[str, Any]], top_k: int
) -> list[dict[str, Any]]:
    """Ask an AI model which passages answer the question best; keep those, best first."""
    if len(hits) <= 1:
        return hits[:top_k]
    listing = "\n\n".join(f"[{hit['n']}] {hit['text'][:800]}" for hit in hits)
    reply = model.invoke(
        [
            (
                "system",
                "Rank the passages by how well they answer the question. Reply with the "
                "passage numbers only, best first, separated by commas.",
            ),
            ("human", f"Question: {query}\n\nPassages:\n\n{listing}"),
        ]
    )
    by_n = {hit["n"]: hit for hit in hits}
    order = [int(n) for n in re.findall(r"\d+", reply.text)]
    picked = [by_n[n] for n in dict.fromkeys(order) if n in by_n]
    picked += [hit for hit in hits if hit not in picked]
    return [{**hit, "n": n} for n, hit in enumerate(picked[:top_k], start=1)]


class KeywordEmbeddings(Embeddings):
    """Embeddings without a model: each word is hashed into one of `dims` slots."""

    COMMON_WORDS = (
        "the and for are but not you all any can had her was one our out has his how its may "
        "new now old see two way who did get got let put say she too use this that with from "
        "have what when where which will your about would there their them they been into "
        "than then these those some such only also just does"
    )
    STOPWORDS = frozenset(COMMON_WORDS.split())

    def __init__(self, dims: int = 256):
        self.dims = dims

    def _embed(self, text: str) -> list[float]:
        vector = [0.0] * self.dims
        for word in re.findall(r"[a-z0-9]{3,}", text.lower()):
            if word in self.STOPWORDS:
                continue
            digest = hashlib.md5(word[:6].encode()).digest()
            slot = int.from_bytes(digest[:4], "little") % self.dims
            vector[slot] += 1.0 if digest[4] & 1 else -1.0
        norm = math.sqrt(sum(v * v for v in vector)) or 1.0
        return [v / norm for v in vector]

    def embed_documents(self, texts: list[str]) -> list[list[float]]:
        return [self._embed(text) for text in texts]

    def embed_query(self, text: str) -> list[float]:
        return self._embed(text)


def as_text(value: Any) -> str:
    """Put a list or object into a prompt as readable text (one list item per paragraph)."""
    if value is None:
        return ""
    if isinstance(value, list):
        return "\n\n".join(as_text(item) for item in value)
    if isinstance(value, dict):
        return json.dumps(value, indent=2, ensure_ascii=False, default=str)
    return str(value)


def tell_agent(error: Exception, request: Any) -> str:
    """When a tool fails, tell the agent (so it can try another way) instead of stopping."""
    return f"The tool failed ({type(error).__name__}): {error}"


# ── Steps ────────────────────────────────────────────────────────────────────


def search(data: FlowData) -> dict[str, Any]:
    """Knowledge Base search · Search the docs

    Finds the 3 passages of the Knowledge Base `product_docs` that best match `question` (by
    meaning and by words, re-ranked by openai:gpt-4o-mini), and saves them numbered for citing
    as `context` and as a list as `sources`.
    """
    query = str(data.get("question") or "")
    embeddings = init_embeddings("openai:text-embedding-3-small", check_embedding_ctx_length=False)
    hits = search_knowledge("product_docs", query, embeddings, top_k=9)
    hits = rerank_passages(init_chat_model("openai:gpt-4o-mini", temperature=0), query, hits, 3)
    return {"context": cite_passages(hits), "sources": hits}


WRITE_PROMPT_MESSAGE = """\
Passages:

{context}

Question: {question}"""

write_prompt_template = ChatPromptTemplate.from_messages(
    [
        ("system", "Answer only from the passages. Cite them like [1]. If they don't say, say you don't know."),
        ("human", WRITE_PROMPT_MESSAGE),
    ]
)


def write_prompt(data: FlowData) -> dict[str, Any]:
    """Instructions · write_prompt

    Fills in {context}, {question} and saves the prompt messages as `prompt`.
    """
    prompt = write_prompt_template.invoke(
        {
            "context": data.get("context", ""),
            "question": data.get("question", ""),
        }
    )
    return {"prompt": prompt.to_messages()}


def answer_it(data: FlowData) -> dict[str, Any]:
    """AI Model · Answer

    Sends `prompt` to openai:gpt-4o-mini and saves the reply as `answer`.
    """
    model = init_chat_model("openai:gpt-4o-mini")
    reply = model.invoke(data["prompt"])
    return {"answer": reply.text}


RESEARCHER_INSTRUCTIONS = "You are a helpful assistant. Use the tools when they help, and say so when you can't find an answer."


def faq(data: FlowData) -> dict[str, Any]:
    """Knowledge Base search · Search the FAQ

    Finds the 4 passages of the Knowledge Base `faq` that best match `query` (by words), and
    saves them numbered for citing as `faq_passages` and as a list as `faq_sources`.
    """
    query = str(data.get("query") or "")
    embeddings = KeywordEmbeddings()
    hits = search_knowledge("faq", query, embeddings, top_k=4, mode="words")
    return {"faq_passages": cite_passages(hits), "faq_sources": hits}


def faq_tool(data: FlowData) -> BaseTool:
    """Knowledge Base search “Search the FAQ” as a tool for agents: faq(query)."""

    @tool("faq", description="Searches the frequently asked questions.")
    def run_tool(query: str) -> str:
        result = faq({**data, "query": query})
        return as_text(result.get("faq_passages"))

    return run_tool


def researcher(data: FlowData) -> dict[str, Any]:
    """Agent · Researcher

    Works on `question` using openai:gpt-4o-mini and the tool faq, and saves its answer as
    `research`.
    """
    agent = create_agent(
        model=init_chat_model("openai:gpt-4o-mini"),
        tools=[faq_tool(data)],
        system_prompt=RESEARCHER_INSTRUCTIONS,
        middleware=[
            ToolErrorMiddleware(tell_agent),
        ],
        name="researcher",
    )
    result = agent.invoke(
        {"messages": [HumanMessage(str(data.get("question", "")))]},
        {"recursion_limit": 100},
    )
    return {"research": result["messages"][-1].text}


# ── Flow ─────────────────────────────────────────────────────────────────────


def build_graph(checkpointer=None, *, store=None, cache=None):
    """Wire the steps into a LangGraph graph.

    Pass a checkpointer (for example InMemorySaver()) to keep a Save Point after every step,
    a store to remember side effects across retries, and a cache for cached steps.
    """
    builder = StateGraph(FlowData, input_schema=FlowInput, output_schema=FlowOutput)

    builder.add_node("search", search)
    builder.add_node("write_prompt", write_prompt)
    builder.add_node("answer_it", answer_it)
    builder.add_node("researcher", researcher)

    builder.add_edge(START, "search")
    builder.add_edge("search", "write_prompt")
    builder.add_edge("write_prompt", "answer_it")
    builder.add_edge("answer_it", "researcher")
    builder.add_edge("researcher", END)
    return builder.compile(checkpointer=checkpointer, store=store, cache=cache)


graph = build_graph()


if __name__ == "__main__":
    example = {"question": "How do I reset my password?"}
    inputs = json.loads(sys.argv[1]) if len(sys.argv) > 1 else example
    result = graph.invoke(inputs)
    print(json.dumps(result, indent=2, ensure_ascii=False, default=str))
