"""Chat with memory

Remembers facts about the user and keeps the chat short.

Generated by Easy Chain 0.3.0 from a version 1 flow spec.
It needs only LangChain and LangGraph:
`pip install -r requirements.txt`, then
`python chat_with_memory.py` to chat in the terminal.

The compiled graph is `graph`; call `build_graph(checkpointer=...)` to keep Save Points.
"""

import json
import re
import sys
import uuid
from typing import Annotated, Any

from langchain.chat_models import init_chat_model
from langchain_core.messages import AnyMessage, RemoveMessage
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langgraph.checkpoint.memory import InMemorySaver
from langgraph.config import get_config, get_store
from langgraph.graph import END, START, StateGraph
from langgraph.graph.message import add_messages
from langgraph.store.memory import InMemoryStore
from typing_extensions import TypedDict

# ── Flow Data ────────────────────────────────────────────────────────────────


class FlowData(TypedDict, total=False):
    """The named fields that steps read and write."""

    messages: Annotated[list[AnyMessage], add_messages]  # The conversation so far; update rule: append
    user_id: str
    memories: str
    memories_summary: str
    prompt: list[AnyMessage]
    last_request: Any


class FlowInput(TypedDict, total=False):
    """What a run takes."""

    messages: Annotated[list[AnyMessage], add_messages]  # The conversation so far; update rule: append
    user_id: str


class FlowOutput(TypedDict, total=False):
    """What a run returns."""

    messages: Annotated[list[AnyMessage], add_messages]  # The conversation so far; update rule: append


# ── Helpers ──────────────────────────────────────────────────────────────────


def memory_namespace(user: Any = None) -> tuple[str, str]:
    """Where a user's memories live: ("memories", user id), or the conversation without one."""
    if not user:
        user = get_config()["configurable"].get("thread_id", "anyone")
    return ("memories", str(user))


def memory_store() -> Any:
    store = get_store()
    if store is None:
        raise RuntimeError(
            "Long-term memory needs a LangGraph store: build_graph(store=InMemoryStore()), "
            "or a database store."
        )
    return store


def remember_fact(namespace: tuple[str, str], fact: str) -> None:
    """Save one fact."""
    if fact.strip():
        memory_store().put(namespace, uuid.uuid4().hex, {"fact": fact.strip()})


def recall_facts(namespace: tuple[str, str], query: str = "", limit: int = 10) -> list[str]:
    """Remembered facts, the ones sharing most words with the query first (newest first otherwise)."""
    items = memory_store().search(namespace, limit=1000)
    items.sort(key=lambda item: item.created_at, reverse=True)
    facts = [item.value.get("fact", "") for item in items]
    if query:

        def stems(text: str) -> set[str]:
            return {w[:4] for w in re.findall(r"[a-z0-9]{3,}", text.lower())}

        wanted = stems(query)
        facts.sort(key=lambda fact: -len(wanted & stems(fact)))
    return facts[:limit]


# ── Steps ────────────────────────────────────────────────────────────────────


def recall(data: FlowData) -> dict[str, Any]:
    """Memory · What do we know?

    Looks up what was remembered for `user_id` that fits `messages`, and saves up to 3 facts as
    `memories`.
    """
    facts = recall_facts(memory_namespace(data.get("user_id")), data["messages"][-1].text if data.get("messages") else "", limit=3)
    return {"memories": "\n".join(f"- {fact}" for fact in facts)}


def summarise(data: FlowData) -> dict[str, Any]:
    """Memory · Summarise chat history

    When `messages` has more than 10 messages, summarises the older ones with openai:gpt-4o-mini
    into `memories_summary` and keeps the latest 10.
    """
    messages = data.get("messages", [])
    if len(messages) <= 10:
        return {}
    older = messages[:-10]
    model = init_chat_model("openai:gpt-4o-mini")
    text = "\n".join(f"{m.type}: {m.text}" for m in older)
    summary = model.invoke(
        "Summarise this conversation so far in a few sentences, keeping names, "
        "numbers and decisions:\n\n" + text
    ).text
    return {"memories_summary": summary, "messages": [RemoveMessage(id=m.id) for m in older]}


WRITE_PROMPT_SYSTEM = """\
You are a friendly assistant.
What you know about the user:
{memories}

Earlier in this chat: {memories_summary}"""

write_prompt_template = ChatPromptTemplate.from_messages(
    [
        ("system", WRITE_PROMPT_SYSTEM),
        MessagesPlaceholder("messages"),
    ]
)


def write_prompt(data: FlowData) -> dict[str, Any]:
    """Instructions · write_prompt

    Fills in {memories}, {memories_summary} and saves the prompt messages as `prompt`.
    """
    prompt = write_prompt_template.invoke(
        {
            "memories": data.get("memories", ""),
            "memories_summary": data.get("memories_summary", ""),
            "messages": data.get("messages", []),
        }
    )
    return {"prompt": prompt.to_messages()}


def reply(data: FlowData) -> dict[str, Any]:
    """AI Model · reply

    Sends `prompt` to openai:gpt-4o-mini and saves the reply as `messages`.
    """
    model = init_chat_model("openai:gpt-4o-mini")
    reply = model.invoke(data["prompt"])
    return {"messages": [reply]}


# Code · last (sets last_request)
def last(data):
    """Remember what the user asked last."""
    return {"last_request": data["messages"][-2].text}


def note(data: FlowData) -> dict[str, Any]:
    """Memory · Remember the request

    Saves `last_request` to long-term memory for `user_id` (LangGraph store).
    """
    remember_fact(memory_namespace(data.get("user_id")), str(data.get("last_request") or ""))
    return {}


# ── Flow ─────────────────────────────────────────────────────────────────────


def build_graph(checkpointer=None, *, store=None, cache=None):
    """Wire the steps into a LangGraph graph.

    Pass a checkpointer (for example InMemorySaver()) to keep a Save Point after every step,
    a store to remember side effects across retries, and a cache for cached steps.
    """
    builder = StateGraph(FlowData, input_schema=FlowInput, output_schema=FlowOutput)

    builder.add_node("recall", recall)
    builder.add_node("summarise", summarise)
    builder.add_node("write_prompt", write_prompt)
    builder.add_node("reply", reply)
    builder.add_node("last", last)
    builder.add_node("note", note)

    builder.add_edge(START, "recall")
    builder.add_edge("recall", "summarise")
    builder.add_edge("summarise", "write_prompt")
    builder.add_edge("write_prompt", "reply")
    builder.add_edge("reply", "last")
    builder.add_edge("last", "note")
    builder.add_edge("note", END)
    return builder.compile(checkpointer=checkpointer, store=store, cache=cache)


graph = build_graph()


if __name__ == "__main__":
    app = build_graph(checkpointer=InMemorySaver(), store=InMemoryStore())
    config = {"configurable": {"thread_id": "terminal"}}
    extra = json.loads(sys.argv[1]) if len(sys.argv) > 1 else {"user_id": "u-42"}
    # Chat in the terminal. Save Points keep the conversation between turns.
    while True:
        try:
            text = input("you> ").strip()
        except (EOFError, KeyboardInterrupt):
            break
        if text:
            result = app.invoke({**extra, "messages": [{"role": "user", "content": text}]}, config)
            print("ai>", result["messages"][-1].text)
