"""Model settings

Generated by Easy Chain 0.1.0 from a version 1 flow spec. It needs only
LangChain and LangGraph: `pip install -r requirements.txt`, then
`python model_settings.py '<inputs as JSON>'`.

The compiled graph is `graph`; call `build_graph(checkpointer=...)` to keep Save Points.
"""

import json
import sys
from typing import Any

from langchain.chat_models import init_chat_model
from langgraph.graph import END, START, StateGraph
from typing_extensions import TypedDict

# ── Flow Data ────────────────────────────────────────────────────────────────


class FlowData(TypedDict, total=False):
    """The named fields that steps read and write."""

    question: str
    first: str
    second: str
    third: str


class FlowInput(TypedDict, total=False):
    """What a run takes."""

    question: str


class FlowOutput(TypedDict, total=False):
    """What a run returns."""

    first: str
    second: str
    third: str


# ── Steps ────────────────────────────────────────────────────────────────────


def openai(data: FlowData) -> dict[str, Any]:
    """AI Model · OpenAI with everything

    Sends `question` to openai:gpt-4.1-mini and saves the reply as `first`.
    """
    model = init_chat_model("openai:gpt-4.1-mini", temperature=0.7, max_tokens=300, reasoning_effort="low", timeout=20.0, max_retries=1, stop=[
    """\


""",
    "END",
])
    reply = model.invoke(data["question"])
    return {"first": reply.text}


def local(data: FlowData) -> dict[str, Any]:
    """AI Model · Local model

    Sends `first` to ollama:llama3.2 and saves the reply as `second`.
    """
    model = init_chat_model("ollama:llama3.2", base_url="http://gpu-box:11434")
    reply = model.invoke(data["first"])
    return {"second": reply.text}


def claude(data: FlowData) -> dict[str, Any]:
    """AI Model · Claude

    Sends `second` to anthropic:claude-sonnet-5-5 and saves the reply as `third`.
    """
    model = init_chat_model("anthropic:claude-sonnet-5-5")
    reply = model.invoke(data["second"])
    return {"third": reply.text}


# ── Flow ─────────────────────────────────────────────────────────────────────


def build_graph(checkpointer=None, *, store=None, cache=None):
    """Wire the steps into a LangGraph graph.

    Pass a checkpointer (for example InMemorySaver()) to keep a Save Point after every step,
    a store to remember side effects across retries, and a cache for cached steps.
    """
    builder = StateGraph(FlowData, input_schema=FlowInput, output_schema=FlowOutput)

    builder.add_node("openai", openai)
    builder.add_node("local", local)
    builder.add_node("claude", claude)

    builder.add_edge(START, "openai")
    builder.add_edge("openai", "local")
    builder.add_edge("local", "claude")
    builder.add_edge("claude", END)
    return builder.compile(checkpointer=checkpointer, store=store, cache=cache)


graph = build_graph()


if __name__ == "__main__":
    example = {"question": ""}
    inputs = json.loads(sys.argv[1]) if len(sys.argv) > 1 else example
    result = graph.invoke(inputs)
    print(json.dumps(result, indent=2, ensure_ascii=False, default=str))
