"""Run policies

Retries, a time limit, a cache, a join that waits for both branches, side effects and a custom
update rule.

Generated by Easy Chain 0.1.0 from a version 1 flow spec. It needs only
LangChain and LangGraph: `pip install -r requirements.txt`, then
`python run_policies.py '<inputs as JSON>'`.

The compiled graph is `graph`; call `build_graph(checkpointer=...)` to keep Save Points.
Some steps have a time limit, so call it with `await graph.ainvoke(...)`.
"""

import asyncio
import hashlib
import json
import os
import re
import sys
from collections.abc import Callable
from typing import Annotated, Any

import httpx
from langgraph.config import get_config, get_store
from langgraph.graph import END, START, StateGraph
from langgraph.types import CachePolicy, RetryPolicy
from typing_extensions import TypedDict

# ── Flow Data ────────────────────────────────────────────────────────────────


# Update rule for `tags`
def combine_tags(old, new):
    """Keep each tag once, in the order first seen."""
    return list(dict.fromkeys((old or []) + (new or [])))


class FlowData(TypedDict, total=False):
    """The named fields that steps read and write."""

    tags: Annotated[list[Any], combine_tags]  # update rule: custom
    text: str
    summary: Any
    receipt: Any


class FlowInput(TypedDict, total=False):
    """What a run takes."""

    text: str


class FlowOutput(TypedDict, total=False):
    """What a run returns."""

    summary: Any
    tags: Annotated[list[Any], combine_tags]  # update rule: custom


RUN_CONFIG: dict[str, Any] = {"recursion_limit": 40, "max_concurrency": 4}


# ── Helpers ──────────────────────────────────────────────────────────────────


def run_once(key: str, action: Callable[[], Any]) -> Any:
    """Do a side effect at most once per key, remembering its result in the LangGraph store."""
    store = get_store()
    if store is None:
        return action()
    saved = store.get(("side_effects",), key)
    if saved is not None:
        return saved.value["result"]
    result = action()
    try:
        store.put(("side_effects",), key, {"result": result})
    except (TypeError, ValueError):
        pass  # results that can't be stored as JSON aren't remembered
    return result


def idempotency_key() -> str:
    """A key that stays the same when this step is retried or resumed after a crash."""
    configurable = get_config()["configurable"]
    task = f"{configurable.get('thread_id', '')}|{configurable.get('checkpoint_ns', '')}"
    return hashlib.sha256(task.encode()).hexdigest()[:32]


def fill(template: str, data: dict[str, Any]) -> str:
    """Put Flow Data values into {field} and environment variables into {secret:NAME}."""

    def value(match: re.Match[str]) -> str:
        name = match.group(1)
        if name.startswith("secret:"):
            return os.environ.get(name.removeprefix("secret:"), "")
        found = data.get(name)
        return "" if found is None else str(found)

    return re.sub(r"\{((?:secret:)?[A-Za-z_][A-Za-z0-9_]*)\}", value, template)


def fill_json(template: str, data: dict[str, Any]) -> str:
    """Like fill(), but writes values as JSON so quotes and newlines can't break the body.

    "{field}" becomes a JSON string, a bare {field} becomes its JSON value, and a
    placeholder inside a longer string is escaped.
    """
    out: list[str] = []
    in_string = False
    pos = 0
    for match in re.finditer(r"\{(?:secret:)?[A-Za-z_][A-Za-z0-9_]*\}", template):
        literal = template[pos : match.start()]
        for i, char in enumerate(literal):
            if char == '"' and (i == 0 or literal[i - 1] != "\\"):
                in_string = not in_string
        text = fill(match.group(0), data)
        name = match.group(0)[1:-1]
        found = text if name.startswith("secret:") else data.get(name)
        after = template[match.end() : match.end() + 1]
        if in_string and literal.endswith('"') and after == '"':
            out.append(literal[:-1] + json.dumps(text, ensure_ascii=False))
            pos = match.end() + 1
            in_string = False
            continue
        out.append(literal)
        if in_string:
            out.append(json.dumps(text, ensure_ascii=False)[1:-1])
        else:
            out.append(json.dumps(found, ensure_ascii=False, default=str))
        pos = match.end()
    out.append(template[pos:])
    return "".join(out)


def in_thread(step: Callable[[Any], Any]) -> Callable[[Any], Any]:
    """Run a step in a worker thread, so LangGraph can enforce its time limit."""

    async def run(data: Any) -> Any:
        return await asyncio.to_thread(step, data)

    run.__name__ = step.__name__
    return run


# ── Steps ────────────────────────────────────────────────────────────────────


# Code · left (sets tags)
def left(data):
    return {"tags": ["left", "shared"]}


# Code · right (sets tags)
def right(data):
    return {"tags": ["right", "shared"]}


# Code · join (sets summary)
def join_code(data):
    return {"summary": ", ".join(data["tags"])}


def join(data: FlowData) -> dict[str, Any]:
    """Code · join

    Runs join_code at most once: a retry or a resume after a crash reuses its first result.
    """
    return run_once(idempotency_key(), lambda: join_code(data))


def notify(data: FlowData) -> dict[str, Any]:
    """Web request · notify

    POST https://hooks.example.com/notify and save the JSON data as `receipt`. It changes
    something elsewhere, so it is sent at most once: a retry or a resume after a crash reuses
    the first answer.
    """
    key = idempotency_key()

    def send() -> Any:
        response = httpx.request(
            "POST",
            "https://hooks.example.com/notify",
            headers={
                "User-Agent": "Mozilla/5.0 (compatible; EasyChain/0.1)",
                "Content-Type": "application/json",
                "Idempotency-Key": key,
            },
            content=fill_json("{\"text\": \"{summary}\"}", data),
            timeout=30,
            follow_redirects=True,
        )
        response.raise_for_status()
        return response.json()

    return {"receipt": run_once(key, send)}


# ── Flow ─────────────────────────────────────────────────────────────────────


def build_graph(checkpointer=None, *, store=None, cache=None):
    """Wire the steps into a LangGraph graph.

    Pass a checkpointer (for example InMemorySaver()) to keep a Save Point after every step,
    a store to remember side effects across retries, and a cache for cached steps.
    """
    builder = StateGraph(FlowData, input_schema=FlowInput, output_schema=FlowOutput)

    builder.add_node(
        "left",
        left,
        retry_policy=RetryPolicy(max_attempts=3, initial_interval=0.5),
    )
    builder.add_node("right", in_thread(right), timeout=5.0, cache_policy=CachePolicy(ttl=60))
    builder.add_node("join", join, defer=True)
    builder.add_node("notify", notify)

    builder.add_edge(START, "left")
    builder.add_edge(START, "right")
    builder.add_edge("left", "join")
    builder.add_edge("right", "join")
    builder.add_edge("join", "notify")
    builder.add_edge("notify", END)
    return builder.compile(checkpointer=checkpointer, store=store, cache=cache)


graph = build_graph()


async def main() -> None:
    app = graph
    config = {**RUN_CONFIG}
    example = {"text": "hello"}
    inputs = json.loads(sys.argv[1]) if len(sys.argv) > 1 else example
    result = await app.ainvoke(inputs, config)
    print(json.dumps(result, indent=2, ensure_ascii=False, default=str))


if __name__ == "__main__":
    asyncio.run(main())
