"""Structured reply

Triages a product review into fields that later steps use directly.

Generated by Easy Chain 0.3.0 from a version 1 flow spec.
It needs only LangChain and LangGraph:
`pip install -r requirements.txt`, then
`python structured_reply.py '<inputs as JSON>'`.

The compiled graph is `graph`; call `build_graph(checkpointer=...)` to keep Save Points.
"""

import json
import os
import sys
from typing import Any, Literal

from langchain.chat_models import init_chat_model
from langchain_core.exceptions import OutputParserException
from langchain_core.messages import AnyMessage
from langchain_core.prompts import ChatPromptTemplate
from langgraph.graph import END, START, StateGraph
from pydantic import BaseModel, Field, ValidationError
from typing_extensions import TypedDict

# ── Flow Data ────────────────────────────────────────────────────────────────


class FlowData(TypedDict, total=False):
    """The named fields that steps read and write."""

    review: str
    prompt: list[AnyMessage]
    verdict: dict[str, Any]
    sentiment: str
    score: float
    reasons: list[Any]
    issues: list[Any]
    urgent: bool
    apology: str


class FlowInput(TypedDict, total=False):
    """What a run takes."""

    review: str


class FlowOutput(TypedDict, total=False):
    """What a run returns."""

    verdict: dict[str, Any]
    sentiment: str
    apology: str


# ── Steps ────────────────────────────────────────────────────────────────────


WRITE_PROMPT_MESSAGE = """\
Review:

{review}"""

write_prompt_template = ChatPromptTemplate.from_messages(
    [
        ("system", "You triage product reviews for the support team."),
        ("human", WRITE_PROMPT_MESSAGE),
    ]
)


def write_prompt(data: FlowData) -> dict[str, Any]:
    """Instructions · write_prompt

    Fills in {review} and saves the prompt messages as `prompt`.
    """
    prompt = write_prompt_template.invoke({"review": data.get("review", "")})
    return {"prompt": prompt.to_messages()}


class TriageReplyIssue(BaseModel):
    """Problems the review mentions."""

    area: Literal["app", "billing", "support", "other"]
    detail: str = Field(description="The problem in a few words.")


class TriageReply(BaseModel):
    """How the support team should handle a review."""

    sentiment: Literal["positive", "negative", "mixed"]
    score: int = Field(description="How happy the customer is, from 1 (angry) to 5 (delighted).")
    reasons: list[str] = Field(description="Short reasons for the score.")
    issues: list[TriageReplyIssue] = Field(description="Problems the review mentions.")
    urgent: bool | None = Field(default=None, description="Someone should reply today.")


def triage(data: FlowData) -> dict[str, Any]:
    """AI Model · Triage the review

    Sends `prompt` to openai:gpt-4o-mini and saves the reply, in the TriageReply format, as
    `verdict`. Each field is also saved on its own: `sentiment`, `score`, `reasons`, `issues`,
    `urgent`.
    """
    model = init_chat_model("openai:gpt-4o-mini")
    structured = model.with_structured_output(TriageReply).with_retry(
        retry_if_exception_type=(ValidationError, OutputParserException),
        stop_after_attempt=3,
    )
    reply = structured.invoke(data["prompt"])
    if reply is None:
        raise ValueError("The model didn't reply in the TriageReply format.")
    result = reply.model_dump()
    return {
        "verdict": result,
        "sentiment": result["sentiment"],
        "score": result["score"],
        "reasons": result["reasons"],
        "issues": result["issues"],
        "urgent": result["urgent"],
    }


def is_negative(data: FlowData) -> dict[str, Any]:
    """Decision · Is it negative?

    Changes no data; route_is_negative below picks the exit.
    """
    return {}


def route_is_negative(data: FlowData) -> str:
    """Pick the exit for the Decision "Is it negative?"."""
    if str(data.get("sentiment") or "").strip().lower() == "negative":
        return "Negative"
    return "Otherwise"


def escalate(data: FlowData) -> dict[str, Any]:
    """AI Model · Draft an apology

    Sends `review` to openai:gpt-4o-mini and saves the reply as `apology`.
    """
    model = init_chat_model(
        "openai:gpt-4o-mini",
        base_url="https://llm.internal/v1",
        api_key=os.environ.get("INTERNAL_LLM_KEY", ""),
    )
    reply = model.invoke(data["review"])
    return {"apology": reply.text}


# ── Flow ─────────────────────────────────────────────────────────────────────


def build_graph(checkpointer=None, *, store=None, cache=None):
    """Wire the steps into a LangGraph graph.

    Pass a checkpointer (for example InMemorySaver()) to keep a Save Point after every step,
    a store to remember side effects across retries, and a cache for cached steps.
    """
    builder = StateGraph(FlowData, input_schema=FlowInput, output_schema=FlowOutput)

    builder.add_node("write_prompt", write_prompt)
    builder.add_node("triage", triage)
    builder.add_node("is_negative", is_negative)
    builder.add_node("escalate", escalate)

    builder.add_edge(START, "write_prompt")
    builder.add_edge("write_prompt", "triage")
    builder.add_edge("triage", "is_negative")
    builder.add_conditional_edges(
        "is_negative",
        route_is_negative,
        {
            "Negative": "escalate",
            "Otherwise": END,
        },
    )
    builder.add_edge("escalate", END)
    return builder.compile(checkpointer=checkpointer, store=store, cache=cache)


graph = build_graph()


if __name__ == "__main__":
    example = {
        "review": "The app crashes every time I upload a photo. Support never answered.",
    }
    inputs = json.loads(sys.argv[1]) if len(sys.argv) > 1 else example
    result = graph.invoke(inputs)
    print(json.dumps(result, indent=2, ensure_ascii=False, default=str))
