"""Use tidy

Generated by Easy Chain 0.2.0 from a version 1 flow spec. It needs only
LangChain and LangGraph: `pip install -r requirements.txt`, then
`python use_tidy.py '<inputs as JSON>'`.

The compiled graph is `graph`; call `build_graph(checkpointer=...)` to keep Save Points.
"""

import json
import sys
from typing import Annotated, Any

from langgraph.graph import END, START, StateGraph
from langgraph.types import Send
from typing_extensions import TypedDict

# ── Flow Data ────────────────────────────────────────────────────────────────


def collect_items(old: list[Any] | None, new: list[Any] | None) -> list[Any]:
    """Update rule for For Each results: None starts a new list, anything else is added."""
    if new is None:
        return []
    return (old or []) + new


class FlowData(TypedDict, total=False):
    """The named fields that steps read and write."""

    words: list[Any]
    text: str
    each_results: Annotated[list[Any], collect_items]  # Results collected by “each” while it runs.
    each_index: float  # The item “each” is working on.
    clean: Any
    tidied: Any
    all_tidy: list[Any]
    one: Any


class FlowInput(TypedDict, total=False):
    """What a run takes."""

    words: list[Any]
    text: str


class FlowOutput(TypedDict, total=False):
    """What a run returns."""

    clean: Any
    tidied: Any
    all_tidy: list[Any]


# ── Sub-flow: Tidy text ──────────────────────────────────────────────────────


class TidyTextData(TypedDict, total=False):
    """The named fields that steps of the sub-flow “Tidy text” read and write."""

    text: str
    style: str
    tidied: Any


class TidyTextInput(TypedDict, total=False):
    """What a run takes."""

    text: str
    style: str


class TidyTextOutput(TypedDict, total=False):
    """What a run returns."""

    tidied: Any


TIDY_TEXT__INPUT_DEFAULTS: dict[str, Any] = {"style": "upper"}


# Code · tidy (sets tidied)
def tidy_text__tidy(data):
    t = data["text"].strip()
    return {"tidied": t.upper() if data.get("style") == "upper" else t.lower()}


def build_tidy_text_graph():
    """The sub-flow “Tidy text” as a graph; it shares the parent's Save Points."""
    builder = StateGraph(
        TidyTextData,
        input_schema=TidyTextInput,
        output_schema=TidyTextOutput,
    )

    builder.add_node("tidy", tidy_text__tidy)

    builder.add_edge(START, "tidy")
    builder.add_edge("tidy", END)
    return builder.compile()


tidy_text_graph = build_tidy_text_graph()


# ── Steps ────────────────────────────────────────────────────────────────────


def separate(data: FlowData) -> dict[str, Any]:
    """Sub-flow · separate

    Runs the flow “Tidy text” with its own Flow Data and saves `clean`.
    """
    result = tidy_text_graph.invoke({**TIDY_TEXT__INPUT_DEFAULTS, "text": data.get("text")})
    return {"clean": result.get("tidied")}


# Sub-flow · shared: runs tidy_text_graph (the flow “Tidy text”) on this flow's data.


def each(data: FlowData) -> dict[str, Any]:
    """For Each · each

    Starts a new list of results; send_each below sends each item of `words` to `per_word`.
    """
    return {"each_results": None}  # None starts the list again


def send_each(data: FlowData) -> list[Send] | str:
    """Send every item of `words` to its own run of the step (they run side by side)."""
    items = data.get("words")
    if items is None:
        items = []
    elif not isinstance(items, list):
        items = [items]
    if not items:
        return "each__done"
    return [
        Send("per_word", {**data, "text": item, "each_index": number})
        for number, item in enumerate(items)
    ]


def per_word_for_each(data: FlowData) -> dict[str, Any]:
    """Run `per_word` for one item of “each” and keep `one`."""
    result = per_word(data) or {}
    return {"each_results": [(data["each_index"], result.get("one"))]}


def each_done(data: FlowData) -> dict[str, Any]:
    """Put the results of “each” in item order and save them as `all_tidy`."""
    collected = sorted(data.get("each_results") or [], key=lambda pair: pair[0])
    return {"all_tidy": [result for _, result in collected]}


def per_word(data: FlowData) -> dict[str, Any]:
    """Sub-flow · per_word

    Runs the flow “Tidy text” with its own Flow Data and saves `one`.
    """
    result = tidy_text_graph.invoke({**TIDY_TEXT__INPUT_DEFAULTS, "text": data.get("text")})
    return {"one": result.get("tidied")}


# ── Flow ─────────────────────────────────────────────────────────────────────


def build_graph(checkpointer=None, *, store=None, cache=None):
    """Wire the steps into a LangGraph graph.

    Pass a checkpointer (for example InMemorySaver()) to keep a Save Point after every step,
    a store to remember side effects across retries, and a cache for cached steps.
    """
    builder = StateGraph(FlowData, input_schema=FlowInput, output_schema=FlowOutput)

    builder.add_node("separate", separate)
    builder.add_node("shared", tidy_text_graph)
    builder.add_node("each", each)
    builder.add_node("each__done", each_done, defer=True)
    builder.add_node("per_word", per_word_for_each)

    builder.add_edge(START, "separate")
    builder.add_edge("separate", "shared")
    builder.add_edge("shared", "each")
    builder.add_conditional_edges("each", send_each, ["per_word", "each__done"])
    builder.add_edge("each__done", END)
    builder.add_edge("per_word", "each__done")
    return builder.compile(checkpointer=checkpointer, store=store, cache=cache)


graph = build_graph()


if __name__ == "__main__":
    example = {"words": [], "text": ""}
    inputs = json.loads(sys.argv[1]) if len(sys.argv) > 1 else example
    result = graph.invoke(inputs)
    print(json.dumps(result, indent=2, ensure_ascii=False, default=str))
