"""Reply to customer feedback

Reads a piece of customer feedback, decides whether it is a complaint, praise or a question, and
drafts the right kind of reply.

Generated by Easy Chain 0.2.0 from a version 1 flow spec. It needs only
LangChain and LangGraph: `pip install -r requirements.txt`, then
`python reply_to_customer_feedback.py '<inputs as JSON>'`.

The compiled graph is `graph`; call `build_graph(checkpointer=...)` to keep Save Points.
"""

import json
import sys
from typing import Any

from langchain.chat_models import init_chat_model
from langchain_core.messages import AnyMessage
from langchain_core.prompts import ChatPromptTemplate
from langgraph.graph import END, START, StateGraph
from typing_extensions import TypedDict

# ── Flow Data ────────────────────────────────────────────────────────────────


class FlowData(TypedDict, total=False):
    """The named fields that steps read and write."""

    feedback: str  # What the customer wrote
    kind: str
    prompt: list[AnyMessage]
    reply: str


class FlowInput(TypedDict, total=False):
    """What a run takes."""

    feedback: str  # What the customer wrote


class FlowOutput(TypedDict, total=False):
    """What a run returns."""

    kind: str
    reply: str


# ── Helpers ──────────────────────────────────────────────────────────────────


def pick_exit(reply: str, exits: list[str], otherwise: str) -> str:
    """Match an AI reply to one of a Decision's exit names (ignoring case)."""
    text = reply.strip().strip(".!\"'`*").lower()
    for name in exits:
        if text == name.lower():
            return name
    for name in exits:
        if name.lower() in text:
            return name
    return otherwise


# ── Steps ────────────────────────────────────────────────────────────────────


WHAT_KIND_EXITS = ["Complaint", "Praise"]
WHAT_KIND_GUIDANCE = """\
Classify the customer's feedback.
Choose the exit that fits best. Reply with the exit name only.

Exits:
- Complaint: the customer is unhappy or angry, something is broken, slow or wrong (a bug, crash or bad experience), or they want a refund
- Praise: the customer is happy, says thanks or loves the product
- Question: none of the above"""


def what_kind(data: FlowData) -> dict[str, Any]:
    """Decision · What kind of feedback?

    Asks openai:gpt-4o-mini which exit fits `feedback` and saves it as `kind`.
    """
    model = init_chat_model("openai:gpt-4o-mini", temperature=0)
    reply = model.invoke([("system", WHAT_KIND_GUIDANCE), ("human", str(data.get("feedback", "")))])
    return {"kind": pick_exit(reply.text, WHAT_KIND_EXITS, "Question")}


def route_what_kind(data: FlowData) -> str:
    """Follow the exit the AI picked for "What kind of feedback?"."""
    return data.get("kind") or "Question"


APOLOGISE_MESSAGE = """\
Write a reply to this complaint:

{feedback}"""

apologise_template = ChatPromptTemplate.from_messages(
    [
        ("system", "You are a caring support agent. Apologise once, explain the next step, and keep it under 80 words."),
        ("human", APOLOGISE_MESSAGE),
    ]
)


def apologise(data: FlowData) -> dict[str, Any]:
    """Instructions · Apologise and help

    Fills in {feedback} and saves the prompt messages as `prompt`.
    """
    prompt = apologise_template.invoke({"feedback": data.get("feedback", "")})
    return {"prompt": prompt.to_messages()}


THANK_MESSAGE = """\
Write a reply to this praise:

{feedback}"""

thank_template = ChatPromptTemplate.from_messages(
    [
        ("system", "You are a warm community manager. Thank the customer in two sentences."),
        ("human", THANK_MESSAGE),
    ]
)


def thank(data: FlowData) -> dict[str, Any]:
    """Instructions · Say thank you

    Fills in {feedback} and saves the prompt messages as `prompt`.
    """
    prompt = thank_template.invoke({"feedback": data.get("feedback", "")})
    return {"prompt": prompt.to_messages()}


ANSWER_MESSAGE = """\
Write a reply to this question:

{feedback}"""

answer_template = ChatPromptTemplate.from_messages(
    [
        ("system", "You are a helpful support agent. Answer briefly and suggest where to learn more."),
        ("human", ANSWER_MESSAGE),
    ]
)


def answer(data: FlowData) -> dict[str, Any]:
    """Instructions · Answer the question

    Fills in {feedback} and saves the prompt messages as `prompt`.
    """
    prompt = answer_template.invoke({"feedback": data.get("feedback", "")})
    return {"prompt": prompt.to_messages()}


def draft_reply(data: FlowData) -> dict[str, Any]:
    """AI Model · Draft the reply

    Sends `prompt` to openai:gpt-4o-mini and saves the reply as `reply`.
    """
    model = init_chat_model("openai:gpt-4o-mini", temperature=0.4)
    reply = model.invoke(data["prompt"])
    return {"reply": reply.text}


# ── Flow ─────────────────────────────────────────────────────────────────────


def build_graph(checkpointer=None, *, store=None, cache=None):
    """Wire the steps into a LangGraph graph.

    Pass a checkpointer (for example InMemorySaver()) to keep a Save Point after every step,
    a store to remember side effects across retries, and a cache for cached steps.
    """
    builder = StateGraph(FlowData, input_schema=FlowInput, output_schema=FlowOutput)

    builder.add_node("what_kind", what_kind)
    builder.add_node("apologise", apologise)
    builder.add_node("thank", thank)
    builder.add_node("answer", answer)
    builder.add_node("draft_reply", draft_reply)

    builder.add_edge(START, "what_kind")
    builder.add_conditional_edges(
        "what_kind",
        route_what_kind,
        {
            "Complaint": "apologise",
            "Praise": "thank",
            "Question": "answer",
        },
    )
    builder.add_edge("apologise", "draft_reply")
    builder.add_edge("thank", "draft_reply")
    builder.add_edge("answer", "draft_reply")
    builder.add_edge("draft_reply", END)
    return builder.compile(checkpointer=checkpointer, store=store, cache=cache)


graph = build_graph()


if __name__ == "__main__":
    example = {
        "feedback": "The app keeps crashing when I upload a photo and I lost my work. Very frustrating.",
    }
    inputs = json.loads(sys.argv[1]) if len(sys.argv) > 1 else example
    result = graph.invoke(inputs)
    print(json.dumps(result, indent=2, ensure_ascii=False, default=str))
