"""Smart summary length

Fetches a page, counts its words with a Code step, and asks for a longer summary only when the
page is long.

Generated by Easy Chain 0.3.0 from a version 1 flow spec.
It needs only LangChain and LangGraph:
`pip install -r requirements.txt`, then
`python smart_summary_length.py '<inputs as JSON>'`.

The compiled graph is `graph`; call `build_graph(checkpointer=...)` to keep Save Points.
"""

import json
import re
import sys
from html.parser import HTMLParser
from typing import Any

import httpx
from langchain.chat_models import init_chat_model
from langchain_core.messages import AnyMessage
from langchain_core.prompts import ChatPromptTemplate
from langgraph.graph import END, START, StateGraph
from typing_extensions import TypedDict

# ── Flow Data ────────────────────────────────────────────────────────────────


class FlowData(TypedDict, total=False):
    """The named fields that steps read and write."""

    url: str  # The page to read
    page: str
    word_count: Any
    prompt: list[AnyMessage]
    summary: str


class FlowInput(TypedDict, total=False):
    """What a run takes."""

    url: str  # The page to read


class FlowOutput(TypedDict, total=False):
    """What a run returns."""

    word_count: Any
    summary: str


# ── Helpers ──────────────────────────────────────────────────────────────────


class _TextExtractor(HTMLParser):
    """Collects the visible text of an HTML page."""

    SKIP = {"script", "style", "noscript", "head", "svg", "template"}
    BLOCK = {
        "p", "div", "br", "li", "tr", "h1", "h2", "h3", "h4", "h5", "h6",
        "section", "article", "header", "footer", "pre", "blockquote",
    }

    def __init__(self) -> None:
        super().__init__()
        self.parts: list[str] = []
        self.skipping = 0

    def handle_starttag(self, tag: str, attrs: list) -> None:
        if tag in self.SKIP:
            self.skipping += 1
        elif tag in self.BLOCK:
            self.parts.append("\n")

    def handle_endtag(self, tag: str) -> None:
        if tag in self.SKIP and self.skipping:
            self.skipping -= 1
        elif tag in self.BLOCK:
            self.parts.append("\n")

    def handle_data(self, text: str) -> None:
        if not self.skipping:
            self.parts.append(text)


def readable_text(page: str) -> str:
    """Turn an HTML page into the plain text a person would read."""
    if "<" not in page:
        return page.strip()
    parser = _TextExtractor()
    parser.feed(page)
    lines = (re.sub(r"\s+", " ", line).strip() for line in "".join(parser.parts).splitlines())
    return re.sub(r"\n{3,}", "\n\n", "\n".join(lines)).strip()


# ── Steps ────────────────────────────────────────────────────────────────────


def fetch_page(data: FlowData) -> dict[str, Any]:
    """Web request · Fetch the page

    GET {url} and save the page text as `page`.
    """
    response = httpx.request(
        "GET",
        data["url"],
        headers={"User-Agent": "Mozilla/5.0 (compatible; EasyChain/0.1)"},
        timeout=30,
        follow_redirects=True,
    )
    response.raise_for_status()
    return {"page": readable_text(response.text)[:20000]}


# Code · Count the words (sets word_count)
def count_words(data):
    """Count the words on the page."""
    words = data.get("page", "").split()
    return {"word_count": len(words)}


def is_long(data: FlowData) -> dict[str, Any]:
    """Decision · Is the page long?

    Changes no data; route_is_long below picks the exit.
    """
    return {}


def route_is_long(data: FlowData) -> str:
    """Pick the exit for the Decision "Is the page long?"."""
    if float(data.get("word_count") or 0) > 800:
        return "Long"
    return "Short"


DETAILED_MESSAGE = """\
Summarise this article in five bullet points.

{page}"""

detailed_template = ChatPromptTemplate.from_messages(
    [
        ("system", "You summarise long articles for busy readers."),
        ("human", DETAILED_MESSAGE),
    ]
)


def detailed(data: FlowData) -> dict[str, Any]:
    """Instructions · Ask for five bullets

    Fills in {page} and saves the prompt messages as `prompt`.
    """
    prompt = detailed_template.invoke({"page": data.get("page", "")})
    return {"prompt": prompt.to_messages()}


BRIEF_MESSAGE = """\
Summarise this page in one sentence.

{page}"""

brief_template = ChatPromptTemplate.from_messages(
    [
        ("system", "You summarise short pages."),
        ("human", BRIEF_MESSAGE),
    ]
)


def brief(data: FlowData) -> dict[str, Any]:
    """Instructions · Ask for one sentence

    Fills in {page} and saves the prompt messages as `prompt`.
    """
    prompt = brief_template.invoke({"page": data.get("page", "")})
    return {"prompt": prompt.to_messages()}


def summarise(data: FlowData) -> dict[str, Any]:
    """AI Model · Summarise

    Sends `prompt` to openai:gpt-4o-mini and saves the reply as `summary`.
    """
    model = init_chat_model("openai:gpt-4o-mini")
    reply = model.invoke(data["prompt"])
    return {"summary": reply.text}


# ── Flow ─────────────────────────────────────────────────────────────────────


def build_graph(checkpointer=None, *, store=None, cache=None):
    """Wire the steps into a LangGraph graph.

    Pass a checkpointer (for example InMemorySaver()) to keep a Save Point after every step,
    a store to remember side effects across retries, and a cache for cached steps.
    """
    builder = StateGraph(FlowData, input_schema=FlowInput, output_schema=FlowOutput)

    builder.add_node("fetch_page", fetch_page)
    builder.add_node("count_words", count_words)
    builder.add_node("is_long", is_long)
    builder.add_node("detailed", detailed)
    builder.add_node("brief", brief)
    builder.add_node("summarise", summarise)

    builder.add_edge(START, "fetch_page")
    builder.add_edge("fetch_page", "count_words")
    builder.add_edge("count_words", "is_long")
    builder.add_conditional_edges(
        "is_long",
        route_is_long,
        {
            "Long": "detailed",
            "Short": "brief",
        },
    )
    builder.add_edge("detailed", "summarise")
    builder.add_edge("brief", "summarise")
    builder.add_edge("summarise", END)
    return builder.compile(checkpointer=checkpointer, store=store, cache=cache)


graph = build_graph()


if __name__ == "__main__":
    example = {"url": "https://en.wikipedia.org/wiki/Large_language_model"}
    inputs = json.loads(sys.argv[1]) if len(sys.argv) > 1 else example
    result = graph.invoke(inputs)
    print(json.dumps(result, indent=2, ensure_ascii=False, default=str))
