"""Summarise several pages

Fetches every page in a list side by side, then writes one combined summary with a bullet per
page.

Generated by Easy Chain 0.3.0 from a version 1 flow spec.
It needs only LangChain and LangGraph:
`pip install -r requirements.txt`, then
`python summarise_several_pages.py '<inputs as JSON>'`.

The compiled graph is `graph`; call `build_graph(checkpointer=...)` to keep Save Points.
"""

import json
import re
import sys
from html.parser import HTMLParser
from typing import Annotated, Any

import httpx
from langchain.chat_models import init_chat_model
from langchain_core.messages import AnyMessage
from langchain_core.prompts import ChatPromptTemplate
from langgraph.graph import END, START, StateGraph
from langgraph.types import RetryPolicy, Send
from typing_extensions import TypedDict

# ── Flow Data ────────────────────────────────────────────────────────────────


def collect_items(old: list[Any] | None, new: list[Any] | None) -> list[Any]:
    """Update rule for For Each results: None starts a new list, anything else is added."""
    if new is None:
        return []
    return (old or []) + new


class FlowData(TypedDict, total=False):
    """The named fields that steps read and write."""

    urls: list[Any]  # The pages to read, one per line
    each_page_results: Annotated[list[Any], collect_items]  # Results collected by “For each page” while it runs.
    each_page_index: float  # The item “For each page” is working on.
    url: Any
    pages: list[Any]
    page: str
    prompt: list[AnyMessage]
    summary: str


class FlowInput(TypedDict, total=False):
    """What a run takes."""

    urls: list[Any]  # The pages to read, one per line


class FlowOutput(TypedDict, total=False):
    """What a run returns."""

    summary: str
    pages: list[Any]


# ── Helpers ──────────────────────────────────────────────────────────────────


class _TextExtractor(HTMLParser):
    """Collects the visible text of an HTML page."""

    SKIP = {"script", "style", "noscript", "head", "svg", "template"}
    BLOCK = {
        "p", "div", "br", "li", "tr", "h1", "h2", "h3", "h4", "h5", "h6",
        "section", "article", "header", "footer", "pre", "blockquote",
    }

    def __init__(self) -> None:
        super().__init__()
        self.parts: list[str] = []
        self.skipping = 0

    def handle_starttag(self, tag: str, attrs: list) -> None:
        if tag in self.SKIP:
            self.skipping += 1
        elif tag in self.BLOCK:
            self.parts.append("\n")

    def handle_endtag(self, tag: str) -> None:
        if tag in self.SKIP and self.skipping:
            self.skipping -= 1
        elif tag in self.BLOCK:
            self.parts.append("\n")

    def handle_data(self, text: str) -> None:
        if not self.skipping:
            self.parts.append(text)


def readable_text(page: str) -> str:
    """Turn an HTML page into the plain text a person would read."""
    if "<" not in page:
        return page.strip()
    parser = _TextExtractor()
    parser.feed(page)
    lines = (re.sub(r"\s+", " ", line).strip() for line in "".join(parser.parts).splitlines())
    return re.sub(r"\n{3,}", "\n\n", "\n".join(lines)).strip()


def as_text(value: Any) -> str:
    """Put a list or object into a prompt as readable text (one list item per paragraph)."""
    if value is None:
        return ""
    if isinstance(value, list):
        return "\n\n".join(as_text(item) for item in value)
    if isinstance(value, dict):
        return json.dumps(value, indent=2, ensure_ascii=False, default=str)
    return str(value)


# ── Steps ────────────────────────────────────────────────────────────────────


def each_page(data: FlowData) -> dict[str, Any]:
    """For Each · For each page

    Starts a new list of results; send_each_page below sends each item of `urls` to
    `fetch_page`.
    """
    return {"each_page_results": None}  # None starts the list again


def send_each_page(data: FlowData) -> list[Send] | str:
    """Send the next 4 items of `urls` to their own runs of the step (they run side by side); the
    next 4 go once those are done.
    """
    items = data.get("urls")
    if items is None:
        items = []
    elif not isinstance(items, list):
        items = [items]
    start = len(data.get("each_page_results") or [])  # how many are done
    if start >= len(items):
        return "each_page__done"
    return [
        Send("fetch_page", {**data, "url": item, "each_page_index": number})
        for number, item in enumerate(items[start : start + 4], start)
    ]


def fetch_page_for_each_page(data: FlowData) -> dict[str, Any]:
    """Run `fetch_page` for one item of “For each page” and keep `page`."""
    result = fetch_page(data) or {}
    return {"each_page_results": [(data["each_page_index"], result.get("page"))]}


def each_page_next(data: FlowData) -> dict[str, Any]:
    """Wait until the items send_each_page sent are done; then send_each_page sends the next."""
    return {}


def each_page_done(data: FlowData) -> dict[str, Any]:
    """Put the results of “For each page” in item order and save them as `pages`."""
    collected = sorted(data.get("each_page_results") or [], key=lambda pair: pair[0])
    return {"pages": [result for _, result in collected]}


def fetch_page(data: FlowData) -> dict[str, Any]:
    """Web request · Fetch the page

    GET {url} and save the page text as `page`.
    """
    response = httpx.request(
        "GET",
        data["url"],
        headers={"User-Agent": "Mozilla/5.0 (compatible; EasyChain/0.1)"},
        timeout=30,
        follow_redirects=True,
    )
    response.raise_for_status()
    return {"page": readable_text(response.text)[:4000]}


WRITE_PROMPT_MESSAGE = """\
Write one bullet point per page, in order.

{pages}"""

write_prompt_template = ChatPromptTemplate.from_messages(
    [
        ("system", "You summarise web pages for busy people. Be accurate and brief."),
        ("human", WRITE_PROMPT_MESSAGE),
    ]
)


def write_prompt(data: FlowData) -> dict[str, Any]:
    """Instructions · Write the prompt

    Fills in {pages} and saves the prompt messages as `prompt`.
    """
    prompt = write_prompt_template.invoke({"pages": as_text(data.get("pages"))})
    return {"prompt": prompt.to_messages()}


def summarise(data: FlowData) -> dict[str, Any]:
    """AI Model · Summarise

    Sends `prompt` to openai:gpt-4o-mini and saves the reply as `summary`.
    """
    model = init_chat_model("openai:gpt-4o-mini", temperature=0.2)
    reply = model.invoke(data["prompt"])
    return {"summary": reply.text}


# ── Flow ─────────────────────────────────────────────────────────────────────


def build_graph(checkpointer=None, *, store=None, cache=None):
    """Wire the steps into a LangGraph graph.

    Pass a checkpointer (for example InMemorySaver()) to keep a Save Point after every step,
    a store to remember side effects across retries, and a cache for cached steps.
    """
    builder = StateGraph(FlowData, input_schema=FlowInput, output_schema=FlowOutput)

    builder.add_node("each_page", each_page)
    builder.add_node("each_page__next", each_page_next)
    builder.add_node("each_page__done", each_page_done, defer=True)
    builder.add_node(
        "fetch_page",
        fetch_page_for_each_page,
        retry_policy=RetryPolicy(max_attempts=2),
    )
    builder.add_node("write_prompt", write_prompt)
    builder.add_node("summarise", summarise)

    builder.add_edge(START, "each_page")
    builder.add_conditional_edges("each_page", send_each_page, ["fetch_page", "each_page__done"])
    builder.add_conditional_edges("each_page__next", send_each_page, ["fetch_page", "each_page__done"])
    builder.add_edge("each_page__done", "write_prompt")
    builder.add_edge("fetch_page", "each_page__next")
    builder.add_edge("write_prompt", "summarise")
    builder.add_edge("summarise", END)
    return builder.compile(checkpointer=checkpointer, store=store, cache=cache)


graph = build_graph()


if __name__ == "__main__":
    example = {
        "urls": [
            "https://en.wikipedia.org/wiki/LangChain",
            "https://en.wikipedia.org/wiki/Honey_bee",
        ],
    }
    inputs = json.loads(sys.argv[1]) if len(sys.argv) > 1 else example
    result = graph.invoke(inputs)
    print(json.dumps(result, indent=2, ensure_ascii=False, default=str))
