"""Support bot over docs

Answers customers from the help centre, citing its sources, and hands a question to a colleague
in the Inbox when the help centre doesn't cover it.

Generated by Easy Chain 0.3.0 from a version 1 flow spec.
It needs LangChain, LangGraph and sqlalchemy, numpy, psycopg:
`pip install -r requirements.txt`, then
`python support_bot_over_docs.py` to chat in the terminal.

The compiled graph is `graph`; call `build_graph(checkpointer=...)` to keep Save Points.
Ask a Human steps and tool approvals pause the run (LangGraph interrupt); resume with
Command(resume=...).
"""

import hashlib
import math
import os
import re
from typing import Annotated, Any

import numpy as np
import sqlalchemy as sa
from langchain.chat_models import init_chat_model
from langchain_core.embeddings import Embeddings
from langchain_core.messages import AnyMessage, RemoveMessage
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langgraph.checkpoint.memory import InMemorySaver
from langgraph.graph import END, START, StateGraph
from langgraph.graph.message import add_messages
from langgraph.types import Command, interrupt
from typing_extensions import TypedDict

# ── Flow Data ────────────────────────────────────────────────────────────────


class FlowData(TypedDict, total=False):
    """The named fields that steps read and write."""

    messages: Annotated[list[AnyMessage], add_messages]  # The conversation so far; update rule: append
    chat_summary: str
    context: str
    sources: list[Any]
    prompt: list[AnyMessage]
    human_answer: str


class FlowInput(TypedDict, total=False):
    """What a run takes."""

    messages: Annotated[list[AnyMessage], add_messages]  # The conversation so far; update rule: append


class FlowOutput(TypedDict, total=False):
    """What a run returns."""

    messages: Annotated[list[AnyMessage], add_messages]  # The conversation so far; update rule: append
    sources: list[Any]


# ── Helpers ──────────────────────────────────────────────────────────────────


KNOWLEDGE_ENGINES: dict[Any, Any] = {}


KNOWLEDGE_VECTORS: dict[Any, Any] = {}


def knowledge_engine() -> sa.Engine:
    """The database that holds the Knowledge Bases (a synchronous SQLAlchemy engine)."""
    url = os.environ.get("EASYCHAIN_KNOWLEDGE_URL") or os.environ.get("EASYCHAIN_DATABASE_URL")
    if not url:
        home = os.environ.get("EASYCHAIN_HOME") or os.path.expanduser("~/.easychain")
        url = f"sqlite:///{os.path.join(home, 'easychain.db')}"
    if url not in KNOWLEDGE_ENGINES:
        scheme, _, rest = url.partition("://")
        if scheme.split("+")[0] in ("postgresql", "postgres"):
            engine = sa.create_engine(f"postgresql+psycopg://{rest}", pool_pre_ping=True)
        else:
            engine = sa.create_engine(f"sqlite://{rest}", connect_args={"timeout": 30})
        KNOWLEDGE_ENGINES[url] = engine
    return KNOWLEDGE_ENGINES[url]


def knowledge_words(query: str) -> list[str]:
    """The words of a question that say what it's about, for full-text search."""
    common_words = (
        "a an and are as at be but by can could did do does for from get got had has have how "
        "i if in into is it its me my no not of on or our so than that the their them then "
        "there these they this to too us was we were what when where which who why will with "
        "would you your about any some please tell know"
    )
    common = set(common_words.split())
    words = [w for w in re.findall(r"[a-z0-9]+", query.lower()) if len(w) > 1]
    return [w for w in words if w not in common][:30]


def knowledge_vector_kind(dims: int) -> str | None:
    """The pgvector type a Knowledge Base's embeddings are indexed and searched as.

    pgvector's HNSW index takes vectors of up to 2,000 numbers. Bigger ones (3,072 from
    text-embedding-3-large) are indexed at half precision (halfvec), which goes up to
    4,000. None means too big to index: search then compares every embedding.
    """
    if dims <= 2000:
        return "vector"
    if dims <= 4000:
        return "halfvec"
    return None


def knowledge_by_meaning(
    conn: Any, base: str, vector: list[float], limit: int
) -> list[tuple[str, float]]:
    """(chunk id, cosine similarity) for the embeddings closest to the question's."""
    if conn.dialect.name == "postgresql":
        found = conn.execute(
            sa.text(
                "SELECT format_type(atttypid, atttypmod), to_regtype('halfvec') IS NOT NULL "
                "FROM pg_attribute WHERE attrelid = 'kb_chunks'::regclass AND attname = 'embedding'"
            )
        ).first()
        if found and found[0] and found[0].startswith("vector"):
            dims = len(vector)
            distance = f"(embedding::vector({dims})) <=> CAST(:q AS vector({dims}))"
            # Order by the same expression the Knowledge Base's index uses, so it is used.
            kind = knowledge_vector_kind(dims)
            if kind == "halfvec" and found[1]:
                order = f"(embedding::halfvec({dims})) <=> CAST(:q AS halfvec({dims}))"
            else:
                order = distance
            sql = (
                f"SELECT id, 1 - ({distance}) FROM kb_chunks WHERE kb_id = :kb "
                f"AND embedding IS NOT NULL ORDER BY {order} LIMIT :n"
            )
            q = "[" + ",".join(f"{v:.7f}" for v in vector) + "]"
            rows = conn.execute(sa.text(sql), {"kb": base, "q": q, "n": limit})
            return [(r[0], float(r[1])) for r in rows]
    # Without pgvector: compare against every chunk with numpy (fine for thousands of chunks).
    stamp = conn.execute(
        sa.text("SELECT updated_at FROM kb_bases WHERE id = :kb"), {"kb": base}
    ).scalar()
    key = (str(conn.engine.url), base)
    cached = KNOWLEDGE_VECTORS.get(key)
    if cached is None or cached[0] != stamp:
        rows = conn.execute(
            sa.text(
                "SELECT id, embedding FROM kb_chunks WHERE kb_id = :kb AND embedding IS NOT NULL"
            ),
            {"kb": base},
        ).all()
        ids = [r[0] for r in rows]
        matrix = (
            np.vstack([np.frombuffer(bytes(r[1]), dtype=np.float32) for r in rows])
            if rows
            else np.zeros((0, len(vector)), dtype=np.float32)
        )
        norms = np.linalg.norm(matrix, axis=1, keepdims=True)
        matrix = matrix / np.where(norms == 0, 1, norms)
        cached = KNOWLEDGE_VECTORS[key] = (stamp, ids, matrix)
    _, ids, matrix = cached
    if not ids or matrix.shape[1] != len(vector):
        return []
    q = np.asarray(vector, dtype=np.float32)
    q = q / (np.linalg.norm(q) or 1.0)
    scores = matrix @ q
    order = np.argsort(-scores)[:limit]
    return [(ids[i], float(scores[i])) for i in order]


def knowledge_by_words(conn: Any, base: str, query: str, limit: int) -> list[str]:
    """Chunk ids that share the most (and the rarest) words with the question."""
    words = knowledge_words(query)
    if not words:
        return []
    if conn.dialect.name == "postgresql":
        q = " | ".join(words)
        sql = (
            "SELECT id FROM kb_chunks WHERE kb_id = :kb AND tsv @@ to_tsquery('english', :q) "
            "ORDER BY ts_rank_cd(tsv, to_tsquery('english', :q)) DESC LIMIT :n"
        )
        return [r[0] for r in conn.execute(sa.text(sql), {"kb": base, "q": q, "n": limit})]
    match = " OR ".join(f'"{w}"' for w in words)
    sql = (
        "SELECT chunk_id FROM kb_chunks_fts WHERE kb_chunks_fts MATCH :q AND kb_id = :kb "
        "ORDER BY bm25(kb_chunks_fts) LIMIT :n"
    )
    return [r[0] for r in conn.execute(sa.text(sql), {"kb": base, "q": match, "n": limit})]


def search_knowledge(
    base: str,
    query: str,
    embeddings: Any,
    top_k: int = 4,
    mode: str = "hybrid",
    min_similarity: float = 0.0,
) -> list[dict[str, Any]]:
    """The passages of a Knowledge Base that best match a question, best first.

    mode: "hybrid" (meaning and words, merged by reciprocal rank fusion), "meaning"
    (embeddings only) or "words" (full-text search only). min_similarity drops passages
    found only by meaning that are less similar than this (0 to 1), so an unrelated
    question can come back with nothing.
    """
    if not query.strip():
        return []
    engine = knowledge_engine()
    pool = max(top_k * 4, 20)
    scores: dict[str, float] = {}
    with engine.connect() as conn:
        by_words = knowledge_by_words(conn, base, query, pool) if mode != "meaning" else []
        by_meaning = []
        if mode != "words":
            near = knowledge_by_meaning(conn, base, embeddings.embed_query(query), pool)
            worded = set(by_words)
            by_meaning = [(cid, sim) for cid, sim in near if sim >= min_similarity or cid in worded]
        similarity = dict(by_meaning)
        for ids in ([cid for cid, _ in by_meaning], by_words):
            for rank, chunk_id in enumerate(ids, start=1):
                scores[chunk_id] = scores.get(chunk_id, 0.0) + 1.0 / (60 + rank)
        best = sorted(scores, key=lambda cid: scores[cid], reverse=True)[:top_k]
        if not best:
            return []
        rows = conn.execute(
            sa.text(
                "SELECT id, doc_id, text, title, source, page, heading FROM kb_chunks "
                "WHERE id IN :ids"
            ).bindparams(sa.bindparam("ids", expanding=True)),
            {"ids": best},
        ).mappings()
        by_id = {row["id"]: dict(row) for row in rows}
    words = set(by_words)
    hits = []
    for cid in best:
        if cid not in by_id:
            continue
        hit = by_id[cid] | {"score": round(scores[cid], 5)}
        if cid in similarity:
            hit["similarity"] = round(similarity[cid], 3)
        hit["matched"] = (
            "both" if cid in similarity and cid in words else "words" if cid in words else "meaning"
        )
        hits.append(hit)
    return [{"n": n, **hit} for n, hit in enumerate(hits, start=1)]


def cite_passages(hits: list[dict[str, Any]]) -> str:
    """Passages numbered for citing: "[1] Title (source, page 3)" then the text."""
    blocks = []
    for hit in hits:
        where = ", ".join(
            part
            for part in (hit.get("source") or "", f"page {hit['page']}" if hit.get("page") else "")
            if part
        )
        title = hit.get("title") or "Untitled"
        heading = hit.get("heading")
        if heading and heading.lower() not in title.lower():
            title = f"{title} › {heading}"
        header = f"[{hit['n']}] {title}" + (f" ({where})" if where else "")
        blocks.append(f"{header}\n{hit['text'].strip()}")
    return "\n\n".join(blocks)


class KeywordEmbeddings(Embeddings):
    """Embeddings without a model: each word is hashed into one of `dims` slots."""

    COMMON_WORDS = (
        "the and for are but not you all any can had her was one our out has his how its may "
        "new now old see two way who did get got let put say she too use this that with from "
        "have what when where which will your about would there their them they been into "
        "than then these those some such only also just does"
    )
    STOPWORDS = frozenset(COMMON_WORDS.split())

    def __init__(self, dims: int = 256):
        self.dims = dims

    def _embed(self, text: str) -> list[float]:
        vector = [0.0] * self.dims
        for word in re.findall(r"[a-z0-9]{3,}", text.lower()):
            if word in self.STOPWORDS:
                continue
            digest = hashlib.md5(word[:6].encode()).digest()
            slot = int.from_bytes(digest[:4], "little") % self.dims
            vector[slot] += 1.0 if digest[4] & 1 else -1.0
        norm = math.sqrt(sum(v * v for v in vector)) or 1.0
        return [v / norm for v in vector]

    def embed_documents(self, texts: list[str]) -> list[list[float]]:
        return [self._embed(text) for text in texts]

    def embed_query(self, text: str) -> list[float]:
        return self._embed(text)


def ask_in_terminal(request: dict[str, Any]) -> dict[str, Any]:
    """Answer an Ask a Human step in the terminal (Easy Chain's Inbox does this in the app)."""
    if "action_requests" in request:
        # An agent wants to use a tool that needs approval (HumanInTheLoopMiddleware).
        decisions = []
        for action in request["action_requests"]:
            print(f"\nThe agent wants to use {action['name']} with {action['args']}")
            if input("approve? [y/n]> ").strip().lower().startswith("y"):
                decisions.append({"type": "approve"})
            else:
                decisions.append({"type": "reject", "message": input("why not?> ")})
        return {"decisions": decisions}
    print(f"\n{request['question']}")
    for name, value in request.get("show", {}).items():
        print(f"  {name}: {value}")
    kind = request.get("kind", "approve")
    if kind == "answer":
        return {"action": "approve", "value": input("answer> ")}
    if kind == "choose":
        options = request.get("options", [])
        for number, option in enumerate(options, start=1):
            print(f"  {number}. {option}")
        picked = input("choose a number> ").strip()
        index = int(picked) - 1 if picked.isdigit() else 0
        return {"action": "approve", "value": options[index if 0 <= index < len(options) else 0]}
    approved = input("approve? [y/n]> ").strip().lower().startswith("y")
    answer: dict[str, Any] = {"action": "approve" if approved else "reject", "comment": input("comment> ")}
    if kind == "edit" and approved:
        edited = input(f"new {request.get('field')} (leave empty to keep it)> ")
        if edited:
            answer["value"] = edited
    return answer


# ── Steps ────────────────────────────────────────────────────────────────────


def tidy_chat(data: FlowData) -> dict[str, Any]:
    """Memory · Keep the chat short

    When `messages` has more than 12 messages, summarises the older ones with openai:gpt-4o-mini
    into `chat_summary` and keeps the latest 12.
    """
    messages = data.get("messages", [])
    if len(messages) <= 12:
        return {}
    older = messages[:-12]
    model = init_chat_model("openai:gpt-4o-mini")
    text = "\n".join(f"{m.type}: {m.text}" for m in older)
    summary = model.invoke(
        "Summarise this conversation so far in a few sentences, keeping names, "
        "numbers and decisions:\n\n" + text
    ).text
    return {"chat_summary": summary, "messages": [RemoveMessage(id=m.id) for m in older]}


def search(data: FlowData) -> dict[str, Any]:
    """Knowledge Base search · Search the help centre

    Finds the 3 passages of the Knowledge Base `help_centre` that best match `messages` (by
    meaning and by words), and saves them numbered for citing as `context` and as a list as
    `sources`.
    """
    query = data["messages"][-1].text if data.get("messages") else ""
    embeddings = KeywordEmbeddings()
    hits = search_knowledge("help_centre", query, embeddings, top_k=3, min_similarity=0.2)
    return {"context": cite_passages(hits), "sources": hits}


def found(data: FlowData) -> dict[str, Any]:
    """Decision · Do the docs cover it?

    Changes no data; route_found below picks the exit.
    """
    return {}


def route_found(data: FlowData) -> str:
    """Pick the exit for the Decision "Do the docs cover it?"."""
    if bool(data.get("sources")):
        return "Found"
    return "Hand over"


WRITE_PROMPT_SYSTEM = """\
You are the support assistant of Bean & Leaf, an online coffee and tea shop.
Answer only from the help-centre passages below, in two or three friendly sentences, and
cite the passages you used like [1]. If they don't answer the question, say so and offer
to pass it to a colleague.
Earlier in this chat: {chat_summary}

Passages:

{context}"""

write_prompt_template = ChatPromptTemplate.from_messages(
    [
        ("system", WRITE_PROMPT_SYSTEM),
        MessagesPlaceholder("messages"),
    ]
)


def write_prompt(data: FlowData) -> dict[str, Any]:
    """Instructions · Answer from the docs

    Fills in {chat_summary}, {context} and saves the prompt messages as `prompt`.
    """
    prompt = write_prompt_template.invoke(
        {
            "chat_summary": data.get("chat_summary", ""),
            "context": data.get("context", ""),
            "messages": data.get("messages", []),
        }
    )
    return {"prompt": prompt.to_messages()}


def ask_colleague(data: FlowData) -> dict[str, Any]:
    """Ask a Human · Ask a colleague

    Pauses the run (a LangGraph interrupt) until a person answers; saves the answer as
    `human_answer`.
    """
    answer = interrupt(
        {
            "step": "ask_colleague",
            "kind": "answer",
            "question": "The help centre doesn't cover this. What should we tell the customer?",
            "show": {"messages": data.get("messages")},
        }
    )
    if not isinstance(answer, dict):  # resumed with a bare value
        answer = {"value": answer}
    return {"human_answer": str(answer.get("value") or "")}


def answer(data: FlowData) -> dict[str, Any]:
    """AI Model · Write the answer

    Sends `prompt` to openai:gpt-4o-mini and saves the reply as `messages`.
    """
    model = init_chat_model("openai:gpt-4o-mini")
    reply = model.invoke(data["prompt"])
    return {"messages": [reply]}


# Code · Send the colleague's answer (sets messages)
def send_answer(data):
    """Add the colleague's answer to the chat."""
    return {"messages": [{"role": "assistant", "content": data["human_answer"]}]}


# ── Flow ─────────────────────────────────────────────────────────────────────


def build_graph(checkpointer=None, *, store=None, cache=None):
    """Wire the steps into a LangGraph graph.

    Pass a checkpointer (for example InMemorySaver()) to keep a Save Point after every step,
    a store to remember side effects across retries, and a cache for cached steps.
    """
    builder = StateGraph(FlowData, input_schema=FlowInput, output_schema=FlowOutput)

    builder.add_node("tidy_chat", tidy_chat)
    builder.add_node("search", search)
    builder.add_node("found", found)
    builder.add_node("write_prompt", write_prompt)
    builder.add_node("ask_colleague", ask_colleague)
    builder.add_node("answer", answer)
    builder.add_node("send_answer", send_answer)

    builder.add_edge(START, "tidy_chat")
    builder.add_edge("tidy_chat", "search")
    builder.add_edge("search", "found")
    builder.add_conditional_edges(
        "found",
        route_found,
        {
            "Found": "write_prompt",
            "Hand over": "ask_colleague",
        },
    )
    builder.add_edge("write_prompt", "answer")
    builder.add_edge("ask_colleague", "send_answer")
    builder.add_edge("answer", END)
    builder.add_edge("send_answer", END)
    return builder.compile(checkpointer=checkpointer, store=store, cache=cache)


graph = build_graph()


if __name__ == "__main__":
    app = build_graph(checkpointer=InMemorySaver())
    config = {"configurable": {"thread_id": "terminal"}}
    # Chat in the terminal. Save Points keep the conversation between turns.
    while True:
        try:
            text = input("you> ").strip()
        except (EOFError, KeyboardInterrupt):
            break
        if text:
            result = app.invoke({"messages": [{"role": "user", "content": text}]}, config)
            while "__interrupt__" in result:
                answer = ask_in_terminal(result["__interrupt__"][0].value)
                result = app.invoke(Command(resume=answer), config)
            print("ai>", result["messages"][-1].text)
