"""SQL analyst

Answers questions about the shop's sales by writing and running read-only SQL, and emails a
report once a person approves it.

Generated by Easy Chain 0.3.0 from a version 1 flow spec.
It needs LangChain, LangGraph and sqlalchemy, psycopg:
`pip install -r requirements.txt`, then
`python sql_analyst.py '<inputs as JSON>'`.

The compiled graph is `graph`; call `build_graph(checkpointer=...)` to keep Save Points.
Ask a Human steps and tool approvals pause the run (LangGraph interrupt); resume with
Command(resume=...).
"""

import datetime
import decimal
import hashlib
import json
import os
import re
import sys
from collections.abc import Callable
from typing import Annotated, Any

import httpx
import sqlalchemy as sa
from langchain.agents import create_agent
from langchain.agents.middleware import (
    HumanInTheLoopMiddleware,
    ModelCallLimitMiddleware,
    ToolCallLimitMiddleware,
    ToolErrorMiddleware,
)
from langchain.agents.structured_output import ToolStrategy
from langchain.chat_models import init_chat_model
from langchain_core.messages import HumanMessage
from langchain_core.tools import BaseTool, tool
from langgraph.checkpoint.memory import InMemorySaver
from langgraph.config import get_config, get_store
from langgraph.graph import END, START, StateGraph
from langgraph.types import Command
from pydantic import BaseModel, Field
from typing_extensions import TypedDict

# ── Flow Data ────────────────────────────────────────────────────────────────


class FlowData(TypedDict, total=False):
    """The named fields that steps read and write."""

    sql: str  # One SQLite SELECT statement.
    report: str  # The report to send, in a few lines.
    question: str
    report_url: str  # Where emailed reports go (a webhook).
    analysis: dict[str, Any]
    answer: str
    sql_used: str


class FlowInput(TypedDict, total=False):
    """What a run takes."""

    question: str
    report_url: str  # Where emailed reports go (a webhook).


class FlowOutput(TypedDict, total=False):
    """What a run returns."""

    answer: str
    sql_used: str


INPUT_DEFAULTS: dict[str, Any] = {"report_url": "https://hooks.example.com/reports"}


# ── Helpers ──────────────────────────────────────────────────────────────────


SQL_ENGINES: dict[Any, Any] = {}


def sql_engine(connection: str) -> sa.Engine:
    """A database from its URL. {secret:NAME} comes from the environment and {home} is the
    Easy Chain folder (~/.easychain, or EASYCHAIN_HOME)."""
    url = re.sub(
        r"\{secret:([A-Za-z_][A-Za-z0-9_]*)\}", lambda m: os.environ.get(m.group(1), ""), connection
    )
    home = os.environ.get("EASYCHAIN_HOME") or os.path.expanduser("~/.easychain")
    url = url.replace("{home}", home)
    if url not in SQL_ENGINES:
        scheme, _, rest = url.partition("://")
        driver = f"postgresql+psycopg://{rest}" if scheme in ("postgresql", "postgres") else url
        SQL_ENGINES[url] = sa.create_engine(driver, pool_pre_ping=True)
    return SQL_ENGINES[url]


def sql_value(value: Any) -> Any:
    """A database value as plain JSON (dates and decimals become text or numbers)."""
    if isinstance(value, decimal.Decimal):
        return float(value)
    if isinstance(value, datetime.date | datetime.time):
        return value.isoformat()
    if isinstance(value, bytes):
        return f"<{len(value)} bytes>"
    return value


def run_sql(
    connection: str,
    sql: str,
    params: dict[str, Any] | None = None,
    *,
    read_only: bool = True,
    max_rows: int = 100,
) -> list[dict[str, Any]]:
    """Run one SQL statement; rows come back as a list of {column: value}.

    Read-only queries run in a read-only transaction, so they can't change anything even if
    the SQL tries to.
    """
    statement = sql.strip().rstrip(";").strip()
    if not statement:
        raise ValueError("There is no SQL to run.")
    if ";" in statement:
        raise ValueError("Run one SQL statement at a time.")
    if read_only and not re.match(
        r"(?is)^(select|with|explain|show|describe|pragma|values)\b", statement
    ):
        raise ValueError(
            "This query is read-only, so it can only read data (SELECT). "
            "Turn off read-only to change data."
        )
    engine = sql_engine(connection)
    with engine.connect() as conn:
        sqlite = conn.dialect.name == "sqlite"
        try:
            if read_only and sqlite:
                conn.exec_driver_sql("PRAGMA query_only = ON")
            elif read_only and conn.dialect.name == "postgresql":
                conn.exec_driver_sql("SET TRANSACTION READ ONLY")
            if params:
                result = conn.execute(sa.text(statement), params)
            else:
                result = conn.exec_driver_sql(statement)
            if not result.returns_rows:
                changed = result.rowcount
                conn.commit()
                return [{"rows_changed": changed}]
            rows = result.mappings().fetchmany(max_rows)
            return [{k: sql_value(v) for k, v in row.items()} for row in rows]
        finally:
            if read_only and sqlite:
                conn.rollback()
                conn.exec_driver_sql("PRAGMA query_only = OFF")


def describe_database(connection: str) -> str:
    """The tables and their columns (with types, keys and row counts), for an AI to write SQL."""
    engine = sql_engine(connection)
    inspector = sa.inspect(engine)
    lines = []
    with engine.connect() as conn:
        for table in inspector.get_table_names():
            columns = inspector.get_columns(table)
            keys = set(inspector.get_pk_constraint(table).get("constrained_columns") or [])
            parts = []
            for column in columns:
                note = " primary key" if column["name"] in keys else ""
                parts.append(f"{column['name']} {column['type']}{note}")
            for fk in inspector.get_foreign_keys(table):
                for col, ref in zip(
                    fk["constrained_columns"], fk["referred_columns"], strict=False
                ):
                    parts.append(f"{col} references {fk['referred_table']}.{ref}")
            count = conn.execute(sa.text(f'SELECT COUNT(*) FROM "{table}"')).scalar()
            lines.append(f"{table} ({count} rows): " + ", ".join(parts))
    return "\n".join(lines) or "The database has no tables."


def as_text(value: Any) -> str:
    """Put a list or object into a prompt as readable text (one list item per paragraph)."""
    if value is None:
        return ""
    if isinstance(value, list):
        return "\n\n".join(as_text(item) for item in value)
    if isinstance(value, dict):
        return json.dumps(value, indent=2, ensure_ascii=False, default=str)
    return str(value)


def fill(template: str, data: dict[str, Any]) -> str:
    """Put Flow Data values into {field} and environment variables into {secret:NAME}."""

    def value(match: re.Match[str]) -> str:
        name = match.group(1)
        if name.startswith("secret:"):
            return os.environ.get(name.removeprefix("secret:"), "")
        found = data.get(name)
        return "" if found is None else str(found)

    return re.sub(r"\{((?:secret:)?[A-Za-z_][A-Za-z0-9_]*)\}", value, template)


def fill_json(template: str, data: dict[str, Any]) -> str:
    """Like fill(), but writes values as JSON so quotes and newlines can't break the body.

    "{field}" becomes a JSON string, a bare {field} becomes its JSON value, and a
    placeholder inside a longer string is escaped.
    """
    out: list[str] = []
    in_string = False
    pos = 0
    for match in re.finditer(r"\{(?:secret:)?[A-Za-z_][A-Za-z0-9_]*\}", template):
        literal = template[pos : match.start()]
        for i, char in enumerate(literal):
            if char == '"' and (i == 0 or literal[i - 1] != "\\"):
                in_string = not in_string
        text = fill(match.group(0), data)
        name = match.group(0)[1:-1]
        found = text if name.startswith("secret:") else data.get(name)
        after = template[match.end() : match.end() + 1]
        if in_string and literal.endswith('"') and after == '"':
            out.append(literal[:-1] + json.dumps(text, ensure_ascii=False))
            pos = match.end() + 1
            in_string = False
            continue
        out.append(literal)
        if in_string:
            out.append(json.dumps(text, ensure_ascii=False)[1:-1])
        else:
            out.append(json.dumps(found, ensure_ascii=False, default=str))
        pos = match.end()
    out.append(template[pos:])
    return "".join(out)


def idempotency_key() -> str:
    """A key that stays the same when this step is retried or resumed after a crash."""
    configurable = get_config()["configurable"]
    task = f"{configurable.get('thread_id', '')}|{configurable.get('checkpoint_ns', '')}"
    return hashlib.sha256(task.encode()).hexdigest()[:32]


def run_once(key: str, action: Callable[[], Any]) -> Any:
    """Do a side effect at most once per key, remembering its result in the LangGraph store."""
    store = get_store()
    if store is None:
        return action()
    saved = store.get(("side_effects",), key)
    if saved is not None:
        return saved.value["result"]
    result = action()
    try:
        store.put(("side_effects",), key, {"result": result})
    except (TypeError, ValueError):
        pass  # results that can't be stored as JSON aren't remembered
    return result


def tell_agent(error: Exception, request: Any) -> str:
    """When a tool fails, tell the agent (so it can try another way) instead of stopping."""
    return f"The tool failed ({type(error).__name__}): {error}"


def ask_in_terminal(request: dict[str, Any]) -> dict[str, Any]:
    """Answer an Ask a Human step in the terminal (Easy Chain's Inbox does this in the app)."""
    if "action_requests" in request:
        # An agent wants to use a tool that needs approval (HumanInTheLoopMiddleware).
        decisions = []
        for action in request["action_requests"]:
            print(f"\nThe agent wants to use {action['name']} with {action['args']}")
            if input("approve? [y/n]> ").strip().lower().startswith("y"):
                decisions.append({"type": "approve"})
            else:
                decisions.append({"type": "reject", "message": input("why not?> ")})
        return {"decisions": decisions}
    print(f"\n{request['question']}")
    for name, value in request.get("show", {}).items():
        print(f"  {name}: {value}")
    kind = request.get("kind", "approve")
    if kind == "answer":
        return {"action": "approve", "value": input("answer> ")}
    if kind == "choose":
        options = request.get("options", [])
        for number, option in enumerate(options, start=1):
            print(f"  {number}. {option}")
        picked = input("choose a number> ").strip()
        index = int(picked) - 1 if picked.isdigit() else 0
        return {"action": "approve", "value": options[index if 0 <= index < len(options) else 0]}
    approved = input("approve? [y/n]> ").strip().lower().startswith("y")
    answer: dict[str, Any] = {"action": "approve" if approved else "reject", "comment": input("comment> ")}
    if kind == "edit" and approved:
        edited = input(f"new {request.get('field')} (leave empty to keep it)> ")
        if edited:
            answer["value"] = edited
    return answer


# ── Steps ────────────────────────────────────────────────────────────────────


ANALYST_INSTRUCTIONS = """\
You are a careful data analyst for Bean & Leaf, an online shop selling coffee, tea and
kitchen goods.
1. Call describe_tables to see the tables.
2. Write one SQLite SELECT query and run it with run_query. If it fails, fix it and try again.
3. Answer only from the query results. Never make numbers up.
Only when the user asks for it, send the answer with email_report (a person approves it first)."""


class AnalystAnswer(BaseModel):
    """The analyst's answer."""

    answer: str = Field(description="The answer in one or two sentences, with the numbers.")
    sql_used: str = Field(description="The SQL query that produced the answer.")


def describe_tables(data: FlowData) -> dict[str, Any]:
    """Database query · Describe the tables

    Describes the database's tables and columns and saves it as `tables`.
    """
    return {"tables": describe_database("sqlite:///{home}/samples/shop.db")}


def describe_tables_tool(data: FlowData) -> BaseTool:
    """Database query “Describe the tables” as a tool for agents: describe_tables()."""

    @tool(
        "describe_tables",
        description="Lists the shop database's tables, columns and row counts. Call it first.",
    )
    def run_tool() -> str:
        result = describe_tables(data)
        return as_text(result.get("tables"))

    return run_tool


def run_query(data: FlowData) -> dict[str, Any]:
    """Database query · Run a query

    Runs the SQL in `sql` on the database (read only) and saves up to 50 rows as `rows`.
    """
    rows = run_sql("sqlite:///{home}/samples/shop.db", str(data.get("sql") or ""), max_rows=50)
    return {"rows": rows}


def run_query_tool(data: FlowData) -> BaseTool:
    """Database query “Run a query” as a tool for agents: run_query(sql)."""

    @tool(
        "run_query",
        description="Runs one read-only SQLite SELECT query and returns up to 50 rows.",
    )
    def run_tool(sql: Annotated[str, "One SQLite SELECT statement."]) -> str:
        result = run_query({**data, "sql": sql})
        return as_text(result.get("rows"))

    return run_tool


def email_report(data: FlowData) -> dict[str, Any]:
    """Web request · Email the report

    POST {report_url} and save the JSON data as `email_receipt`. It changes something elsewhere,
    so it is sent at most once: a retry or a resume after a crash reuses the first answer.
    """
    key = idempotency_key()

    def send() -> Any:
        response = httpx.request(
            "POST",
            data["report_url"],
            headers={
                "User-Agent": "Mozilla/5.0 (compatible; EasyChain/0.1)",
                "Content-Type": "application/json",
                "Idempotency-Key": key,
            },
            content=fill_json("{\"report\": \"{report}\"}", data),
            timeout=30,
            follow_redirects=True,
        )
        response.raise_for_status()
        return response.json()

    return {"email_receipt": run_once(key, send)}


def email_report_tool(data: FlowData) -> BaseTool:
    """Web request “Email the report” as a tool for agents: email_report(report)."""

    @tool(
        "email_report",
        description="Emails a short report to the team. A person approves it first.",
    )
    def run_tool(report: Annotated[str, "The report to send, in a few lines."]) -> str:
        result = email_report({**data, "report": report})
        return as_text(result.get("email_receipt"))

    return run_tool


def analyst(data: FlowData) -> dict[str, Any]:
    """Agent · Analyst

    Works on `question` using openai:gpt-4o-mini and the tools describe_tables, run_query and
    email_report, and saves its answer as `analysis`.
    """
    agent = create_agent(
        model=init_chat_model("openai:gpt-4o-mini"),
        tools=[
            describe_tables_tool(data),
            run_query_tool(data),
            email_report_tool(data),
        ],
        system_prompt=ANALYST_INSTRUCTIONS,
        middleware=[
            HumanInTheLoopMiddleware(
                interrupt_on={
                    "email_report": {"allowed_decisions": ["approve", "edit", "reject"]},
                },
                description_prefix="The agent wants to use a tool that needs your approval",
            ),
            ModelCallLimitMiddleware(run_limit=10, exit_behavior="end"),
            ToolCallLimitMiddleware(run_limit=8),
            ToolErrorMiddleware(tell_agent),
        ],
        response_format=ToolStrategy(AnalystAnswer),
        name="analyst",
    )
    result = agent.invoke(
        {"messages": [HumanMessage(str(data.get("question", "")))]},
        {"recursion_limit": 100},
    )
    if result.get("structured_response") is None:
        # A limit (or an error the agent was told about) ended it before it answered.
        raise ValueError(f"The agent stopped before it answered: {result['messages'][-1].text}")
    answer = result["structured_response"].model_dump()
    return {"analysis": answer, "answer": answer["answer"], "sql_used": answer["sql_used"]}


# ── Flow ─────────────────────────────────────────────────────────────────────


def build_graph(checkpointer=None, *, store=None, cache=None):
    """Wire the steps into a LangGraph graph.

    Pass a checkpointer (for example InMemorySaver()) to keep a Save Point after every step,
    a store to remember side effects across retries, and a cache for cached steps.
    """
    builder = StateGraph(FlowData, input_schema=FlowInput, output_schema=FlowOutput)

    builder.add_node("analyst", analyst)

    builder.add_edge(START, "analyst")
    builder.add_edge("analyst", END)
    return builder.compile(checkpointer=checkpointer, store=store, cache=cache)


graph = build_graph()


if __name__ == "__main__":
    app = build_graph(checkpointer=InMemorySaver())
    config = {"configurable": {"thread_id": "terminal"}}
    example = {
        "question": "Which product category brings in the most money?",
        "report_url": "https://hooks.example.com/reports",
    }
    inputs = json.loads(sys.argv[1]) if len(sys.argv) > 1 else example
    result = app.invoke({**INPUT_DEFAULTS, **inputs}, config)
    while "__interrupt__" in result:
        answer = ask_in_terminal(result["__interrupt__"][0].value)
        result = app.invoke(Command(resume=answer), config)
    print(json.dumps(result, indent=2, ensure_ascii=False, default=str))
