"""Chat assistant

A friendly assistant that remembers the conversation. Change its role and rules to make it
yours.

Generated by Easy Chain 0.2.0 from a version 1 flow spec. It needs only
LangChain and LangGraph: `pip install -r requirements.txt`, then
`python chat_assistant.py` to chat in the terminal.

The compiled graph is `graph`; call `build_graph(checkpointer=...)` to keep Save Points.
"""

from typing import Annotated, Any

from langchain.chat_models import init_chat_model
from langchain_core.messages import AnyMessage
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langgraph.checkpoint.memory import InMemorySaver
from langgraph.graph import END, START, StateGraph
from langgraph.graph.message import add_messages
from typing_extensions import TypedDict

# ── Flow Data ────────────────────────────────────────────────────────────────


class FlowData(TypedDict, total=False):
    """The named fields that steps read and write."""

    messages: Annotated[list[AnyMessage], add_messages]  # The conversation so far; update rule: append
    prompt: list[AnyMessage]


class FlowInput(TypedDict, total=False):
    """What a run takes."""

    messages: Annotated[list[AnyMessage], add_messages]  # The conversation so far; update rule: append


class FlowOutput(TypedDict, total=False):
    """What a run returns."""

    messages: Annotated[list[AnyMessage], add_messages]  # The conversation so far; update rule: append


# ── Steps ────────────────────────────────────────────────────────────────────


INSTRUCTIONS_SYSTEM = """\
You are a friendly, concise assistant.
Answer in plain language. If you don't know something, say so."""

instructions_template = ChatPromptTemplate.from_messages(
    [
        ("system", INSTRUCTIONS_SYSTEM),
        MessagesPlaceholder("messages"),
    ]
)


def instructions(data: FlowData) -> dict[str, Any]:
    """Instructions · Role and rules

    Saves the prompt messages as `prompt`.
    """
    prompt = instructions_template.invoke({"messages": data.get("messages", [])})
    return {"prompt": prompt.to_messages()}


def reply(data: FlowData) -> dict[str, Any]:
    """AI Model · Reply

    Sends `prompt` to openai:gpt-4o-mini and saves the reply as `messages`.
    """
    model = init_chat_model("openai:gpt-4o-mini")
    reply = model.invoke(data["prompt"])
    return {"messages": [reply]}


# ── Flow ─────────────────────────────────────────────────────────────────────


def build_graph(checkpointer=None, *, store=None, cache=None):
    """Wire the steps into a LangGraph graph.

    Pass a checkpointer (for example InMemorySaver()) to keep a Save Point after every step,
    a store to remember side effects across retries, and a cache for cached steps.
    """
    builder = StateGraph(FlowData, input_schema=FlowInput, output_schema=FlowOutput)

    builder.add_node("instructions", instructions)
    builder.add_node("reply", reply)

    builder.add_edge(START, "instructions")
    builder.add_edge("instructions", "reply")
    builder.add_edge("reply", END)
    return builder.compile(checkpointer=checkpointer, store=store, cache=cache)


graph = build_graph()


if __name__ == "__main__":
    app = build_graph(checkpointer=InMemorySaver())
    config = {"configurable": {"thread_id": "terminal"}}
    # Chat in the terminal. Save Points keep the conversation between turns.
    while True:
        try:
            text = input("you> ").strip()
        except (EOFError, KeyboardInterrupt):
            break
        if text:
            result = app.invoke({"messages": [{"role": "user", "content": text}]}, config)
            print("ai>", result["messages"][-1].text)
