"""Approval workflow

Drafts a reply to a customer email, waits for a person to edit and approve it (for as long as it
takes), then sends it.

Generated by Easy Chain 0.2.0 from a version 1 flow spec. It needs only
LangChain and LangGraph: `pip install -r requirements.txt`, then
`python approval_workflow.py '<inputs as JSON>'`.

The compiled graph is `graph`; call `build_graph(checkpointer=...)` to keep Save Points.
Ask a Human steps pause the run (LangGraph interrupt); resume with Command(resume=...).
"""

import hashlib
import json
import sys
from collections.abc import Callable
from typing import Any

from langchain.chat_models import init_chat_model
from langchain_core.messages import AnyMessage
from langchain_core.prompts import ChatPromptTemplate
from langgraph.checkpoint.memory import InMemorySaver
from langgraph.config import get_config, get_store
from langgraph.graph import END, START, StateGraph
from langgraph.types import Command, interrupt
from typing_extensions import TypedDict

# ── Flow Data ────────────────────────────────────────────────────────────────


class FlowData(TypedDict, total=False):
    """The named fields that steps read and write."""

    email: str  # The customer's email
    prompt: list[AnyMessage]
    draft: str
    decision: str
    decision_comment: str
    sent: Any
    sent_reply: Any


class FlowInput(TypedDict, total=False):
    """What a run takes."""

    email: str  # The customer's email


class FlowOutput(TypedDict, total=False):
    """What a run returns."""

    sent: Any
    sent_reply: Any
    decision: str
    decision_comment: str


# ── Helpers ──────────────────────────────────────────────────────────────────


def run_once(key: str, action: Callable[[], Any]) -> Any:
    """Do a side effect at most once per key, remembering its result in the LangGraph store."""
    store = get_store()
    if store is None:
        return action()
    saved = store.get(("side_effects",), key)
    if saved is not None:
        return saved.value["result"]
    result = action()
    try:
        store.put(("side_effects",), key, {"result": result})
    except (TypeError, ValueError):
        pass  # results that can't be stored as JSON aren't remembered
    return result


def idempotency_key() -> str:
    """A key that stays the same when this step is retried or resumed after a crash."""
    configurable = get_config()["configurable"]
    task = f"{configurable.get('thread_id', '')}|{configurable.get('checkpoint_ns', '')}"
    return hashlib.sha256(task.encode()).hexdigest()[:32]


def ask_in_terminal(request: dict[str, Any]) -> dict[str, Any]:
    """Answer an Ask a Human step in the terminal (Easy Chain's Inbox does this in the app)."""
    print(f"\n{request['question']}")
    for name, value in request.get("show", {}).items():
        print(f"  {name}: {value}")
    kind = request.get("kind", "approve")
    if kind == "answer":
        return {"action": "approve", "value": input("answer> ")}
    if kind == "choose":
        options = request.get("options", [])
        for number, option in enumerate(options, start=1):
            print(f"  {number}. {option}")
        picked = input("choose a number> ").strip()
        index = int(picked) - 1 if picked.isdigit() else 0
        return {"action": "approve", "value": options[index if 0 <= index < len(options) else 0]}
    approved = input("approve? [y/n]> ").strip().lower().startswith("y")
    answer: dict[str, Any] = {"action": "approve" if approved else "reject", "comment": input("comment> ")}
    if kind == "edit" and approved:
        edited = input(f"new {request.get('field')} (leave empty to keep it)> ")
        if edited:
            answer["value"] = edited
    return answer


# ── Steps ────────────────────────────────────────────────────────────────────


WRITE_PROMPT_MESSAGE = """\
Write a reply to this customer email. Keep it under 80 words.

{email}"""

write_prompt_template = ChatPromptTemplate.from_messages(
    [
        ("system", "You write short, warm and accurate replies for a customer support team."),
        ("human", WRITE_PROMPT_MESSAGE),
    ]
)


def write_prompt(data: FlowData) -> dict[str, Any]:
    """Instructions · Write the prompt

    Fills in {email} and saves the prompt messages as `prompt`.
    """
    prompt = write_prompt_template.invoke({"email": data.get("email", "")})
    return {"prompt": prompt.to_messages()}


def draft_reply(data: FlowData) -> dict[str, Any]:
    """AI Model · Draft the reply

    Sends `prompt` to openai:gpt-4o-mini and saves the reply as `draft`.
    """
    model = init_chat_model("openai:gpt-4o-mini")
    reply = model.invoke(data["prompt"])
    return {"draft": reply.text}


def review(data: FlowData) -> dict[str, Any]:
    """Ask a Human · Check the reply

    Pauses the run (a LangGraph interrupt) until a person edits `draft` and approves or rejects;
    saves the decision as `decision`.
    """
    answer = interrupt(
        {
            "step": "review",
            "kind": "edit",
            "question": "Send this reply to the customer?",
            "show": {"email": data.get("email")},
            "field": "draft",
            "value": data.get("draft"),
        }
    )
    if not isinstance(answer, dict):  # resumed with a bare value
        answer = {"value": answer}
    approved = answer.get("action", "approve") == "approve"
    update: dict[str, Any] = {
        "decision": "Approved" if approved else "Rejected",
        "decision_comment": str(answer.get("comment") or ""),
    }
    if approved and answer.get("value") is not None:
        update["draft"] = answer["value"]
    return update


def route_review(data: FlowData) -> str:
    """Follow the answer given at "Check the reply"."""
    return "Approved" if data.get("decision") == "Approved" else "Rejected"


# Code · Send it (sets sent, sent_reply)
def send_code(data):
    """Send the reply (here it is only recorded; connect a Web request to really send it)."""
    return {"sent": True, "sent_reply": data["draft"]}


def send(data: FlowData) -> dict[str, Any]:
    """Code · Send it

    Runs send_code at most once: a retry or a resume after a crash reuses its first result.
    """
    return run_once(idempotency_key(), lambda: send_code(data))


# ── Flow ─────────────────────────────────────────────────────────────────────


def build_graph(checkpointer=None, *, store=None, cache=None):
    """Wire the steps into a LangGraph graph.

    Pass a checkpointer (for example InMemorySaver()) to keep a Save Point after every step,
    a store to remember side effects across retries, and a cache for cached steps.
    """
    builder = StateGraph(FlowData, input_schema=FlowInput, output_schema=FlowOutput)

    builder.add_node("write_prompt", write_prompt)
    builder.add_node("draft_reply", draft_reply)
    builder.add_node("review", review)
    builder.add_node("send", send)

    builder.add_edge(START, "write_prompt")
    builder.add_edge("write_prompt", "draft_reply")
    builder.add_edge("draft_reply", "review")
    builder.add_conditional_edges("review", route_review, {"Approved": "send", "Rejected": END})
    builder.add_edge("send", END)
    return builder.compile(checkpointer=checkpointer, store=store, cache=cache)


graph = build_graph()


if __name__ == "__main__":
    app = build_graph(checkpointer=InMemorySaver())
    config = {"configurable": {"thread_id": "terminal"}}
    example = {
        "email": "Hi, my order 1234 hasn't arrived yet. Can you check where it is?",
    }
    inputs = json.loads(sys.argv[1]) if len(sys.argv) > 1 else example
    result = app.invoke(inputs, config)
    while "__interrupt__" in result:
        answer = ask_in_terminal(result["__interrupt__"][0].value)
        result = app.invoke(Command(resume=answer), config)
    print(json.dumps(result, indent=2, ensure_ascii=False, default=str))
