"""Tidy text

Generated by Easy Chain 0.3.0 from a version 1 flow spec.
It needs only LangChain and LangGraph:
`pip install -r requirements.txt`, then
`python tidy_text.py '<inputs as JSON>'`.

The compiled graph is `graph`; call `build_graph(checkpointer=...)` to keep Save Points.
"""

import json
import sys
from typing import Any

from langgraph.graph import END, START, StateGraph
from typing_extensions import TypedDict

# ── Flow Data ────────────────────────────────────────────────────────────────


class FlowData(TypedDict, total=False):
    """The named fields that steps read and write."""

    text: str
    style: str
    tidied: Any


class FlowInput(TypedDict, total=False):
    """What a run takes."""

    text: str
    style: str


class FlowOutput(TypedDict, total=False):
    """What a run returns."""

    tidied: Any


INPUT_DEFAULTS: dict[str, Any] = {"style": "upper"}


# ── Steps ────────────────────────────────────────────────────────────────────


# Code · tidy (sets tidied)
def tidy(data):
    t = data["text"].strip()
    return {"tidied": t.upper() if data.get("style") == "upper" else t.lower()}


# ── Flow ─────────────────────────────────────────────────────────────────────


def build_graph(checkpointer=None, *, store=None, cache=None):
    """Wire the steps into a LangGraph graph.

    Pass a checkpointer (for example InMemorySaver()) to keep a Save Point after every step,
    a store to remember side effects across retries, and a cache for cached steps.
    """
    builder = StateGraph(FlowData, input_schema=FlowInput, output_schema=FlowOutput)

    builder.add_node("tidy", tidy)

    builder.add_edge(START, "tidy")
    builder.add_edge("tidy", END)
    return builder.compile(checkpointer=checkpointer, store=store, cache=cache)


graph = build_graph()


if __name__ == "__main__":
    example = {"text": "", "style": "upper"}
    inputs = json.loads(sys.argv[1]) if len(sys.argv) > 1 else example
    result = graph.invoke({**INPUT_DEFAULTS, **inputs})
    print(json.dumps(result, indent=2, ensure_ascii=False, default=str))
