"""Loose ends

Generated by Easy Chain 0.1.0 from a version 1 flow spec. It needs only
LangChain and LangGraph: `pip install -r requirements.txt`, then
`python loose_ends.py '<inputs as JSON>'`.

The compiled graph is `graph`; call `build_graph(checkpointer=...)` to keep Save Points.
"""

import json
import sys
from typing import Any

from langchain.chat_models import init_chat_model
from langchain_core.messages import AnyMessage
from langgraph.graph import END, START, StateGraph
from typing_extensions import TypedDict

# ── Flow Data ────────────────────────────────────────────────────────────────


class FlowData(TypedDict, total=False):
    """The named fields that steps read and write."""

    topic: str
    answer: str
    prompt: list[AnyMessage]


class FlowInput(TypedDict, total=False):
    """What a run takes."""

    topic: str


class FlowOutput(TypedDict, total=False):
    """What a run returns."""

    answer: str


# ── Steps ────────────────────────────────────────────────────────────────────


def ask(data: FlowData) -> dict[str, Any]:
    """AI Model · ask

    Sends `topic` to openai:gpt-4o-mini and saves the reply as `answer`.
    """
    model = init_chat_model("openai:gpt-4o-mini")
    reply = model.invoke(data["topic"])
    return {"answer": reply.text}


# Not connected to Input, so not included: orphan (orphan)


# ── Flow ─────────────────────────────────────────────────────────────────────


def build_graph(checkpointer=None):
    """Wire the steps into a LangGraph graph.

    Pass a checkpointer (for example InMemorySaver()) to keep a Save Point after every step.
    """
    builder = StateGraph(FlowData, input_schema=FlowInput, output_schema=FlowOutput)

    builder.add_node("ask", ask)

    builder.add_edge(START, "ask")
    builder.add_edge("ask", END)
    return builder.compile(checkpointer=checkpointer)


graph = build_graph()


if __name__ == "__main__":
    example = {"topic": ""}
    inputs = json.loads(sys.argv[1]) if len(sys.argv) > 1 else example
    result = graph.invoke(inputs)
    print(json.dumps(result, indent=2, ensure_ascii=False, default=str))
