"""Keep a tally

Flow Data update rules and a guarded loop.

Generated by Easy Chain 0.2.0 from a version 1 flow spec. It needs only
LangChain and LangGraph: `pip install -r requirements.txt`, then
`python keep_a_tally.py '<inputs as JSON>'`.

The compiled graph is `graph`; call `build_graph(checkpointer=...)` to keep Save Points.
"""

import json
import math
import operator
import sys
from typing import Annotated, Any

from langgraph.graph import END, START, StateGraph
from typing_extensions import TypedDict

# ── Flow Data ────────────────────────────────────────────────────────────────


def merge_dicts(old: dict[str, Any] | None, new: dict[str, Any] | None) -> dict[str, Any]:
    """Update rule "merge": add the new keys to the existing object."""
    return {**(old or {}), **(new or {})}


class FlowData(TypedDict, total=False):
    """The named fields that steps read and write."""

    notes: Annotated[list[Any], operator.add]  # One note per round; update rule: append
    total: Annotated[float, operator.add]  # update rule: add
    meta: Annotated[dict[str, Any], merge_dicts]  # update rule: merge
    log: Annotated[str, operator.add]  # update rule: append
    rounds: float


class FlowInput(TypedDict, total=False):
    """What a run takes."""

    rounds: float


class FlowOutput(TypedDict, total=False):
    """What a run returns."""

    notes: Annotated[list[Any], operator.add]  # One note per round; update rule: append
    total: Annotated[float, operator.add]  # update rule: add
    meta: Annotated[dict[str, Any], merge_dicts]  # update rule: merge
    log: Annotated[str, operator.add]  # update rule: append


INPUT_DEFAULTS: dict[str, Any] = {"rounds": 3}


# ── Steps ────────────────────────────────────────────────────────────────────


# Code · Add one (sets notes, total, meta, log)
def tally(data):
    """Add a note and one to the total."""
    n = len(data.get("notes", []))
    return {"notes": [f"round {n + 1}"], "total": 1, "meta": {f"r{n}": math.floor(n)}, "log": "."}


def again(data: FlowData) -> dict[str, Any]:
    """Decision · Another round?

    Changes no data; route_again below picks the exit.
    """
    return {}


def route_again(data: FlowData) -> str:
    """Pick the exit for the Decision "Another round?"."""
    if data.get("total") < data.get("rounds"):
        return "Again"
    return "Done"


# ── Flow ─────────────────────────────────────────────────────────────────────


def build_graph(checkpointer=None, *, store=None, cache=None):
    """Wire the steps into a LangGraph graph.

    Pass a checkpointer (for example InMemorySaver()) to keep a Save Point after every step,
    a store to remember side effects across retries, and a cache for cached steps.
    """
    builder = StateGraph(FlowData, input_schema=FlowInput, output_schema=FlowOutput)

    builder.add_node("tally", tally)
    builder.add_node("again", again)

    builder.add_edge(START, "tally")
    builder.add_edge("tally", "again")
    builder.add_conditional_edges("again", route_again, {"Again": "tally", "Done": END})
    return builder.compile(checkpointer=checkpointer, store=store, cache=cache)


graph = build_graph()


if __name__ == "__main__":
    example = {"rounds": 3}
    inputs = json.loads(sys.argv[1]) if len(sys.argv) > 1 else example
    result = graph.invoke({**INPUT_DEFAULTS, **inputs})
    print(json.dumps(result, indent=2, ensure_ascii=False, default=str))
